-- Estructura organizacional completa para asignaciones jerárquicas de empleados.
with units(code,name,type_name,parent_name,sort_order) as (values
('DG','Dirección General','Dirección',null,1),
('DCOM','Dirección de Comunicaciones','Dirección','Dirección General',10),('DRH','Dirección de Recursos Humanos','Dirección','Dirección General',20),
('DAF','Dirección Administrativa y Financiera','Dirección','Dirección General',30),('DT','Dirección Técnica','Dirección','Dirección General',40),
('DCO','Dirección Comercial','Dirección','Dirección General',50),('DPD','Dirección de Planificación y Desarrollo','Dirección','Dirección General',60),
('TIC','Departamento de Tecnología de la Información y Comunicación (TIC)','Departamento','Dirección General',70),
('DCAO','Departamento de Control y Análisis de Operaciones','Departamento','Dirección General',80),('DJUR','Departamento Jurídico','Departamento','Dirección General',90),
('OAI','Oficina de Acceso a la Información','Departamento','Dirección General',100),
('DRP','División de Relaciones Públicas','División','Dirección de Comunicaciones',11),('DPSC','División de Participación Social y Ciudadana','División','Dirección de Comunicaciones',12),
('SPRE','Sección de Prensa','Sección','División de Relaciones Públicas',111),('SPRO','Sección de Protocolo y Eventos','Sección','Dirección de Comunicaciones',112),('SRSM','Sección de Redes Sociales y Medios Digitales','Sección','Dirección de Comunicaciones',113),
('SRCN','Sección de Registro, Control y Nómina','Sección','Dirección de Recursos Humanos',201),('SEDC','Sección de Evaluación del Desempeño y Capacitaciones','Sección','Dirección de Recursos Humanos',202),('SOTC','Sección de Organización del Trabajo y Compensaciones','Sección','Dirección de Recursos Humanos',203),
('DDIC','Departamento de Desarrollo Institucional y Calidad en la Gestión','Departamento','Dirección de Planificación y Desarrollo',601),('SCIN','Sección de Cooperación Internacional','Sección','Dirección de Planificación y Desarrollo',602),('DFME','Departamento de Formulación, Monitoreo y Evaluación de Planes, Programas y Proyectos','Departamento','Dirección de Planificación y Desarrollo',603),
('SATIC','Sección de Administración de Servicios TIC','Sección','Departamento de Tecnología de la Información y Comunicación (TIC)',701),('SOTIC','Sección de Operaciones TIC','Sección','Departamento de Tecnología de la Información y Comunicación (TIC)',702),
('DGCOM','Departamento de Gestión Comercial','Departamento','Dirección Comercial',501),('DGOP','Departamento de Gestión Operativa','Departamento','Dirección Comercial',502),
('SGCO','Sección de Gestión de Cobros','Sección','Departamento de Gestión Comercial',511),('SFAC','Sección de Facturación','Sección','Departamento de Gestión Comercial',512),('SACL','Sección de Atención al Cliente','Sección','Departamento de Gestión Comercial',513),
('CPAE','Centros de Pagos Externos','Centro','Departamento de Gestión Comercial',514),('CSCL','Centros de Servicio al Cliente','Centro','Departamento de Gestión Comercial',515),
('SCAU','Sección de Catastro de Usuarios','Sección','Departamento de Gestión Operativa',521),('SMIC','Sección de Micromedición','Sección','Departamento de Gestión Operativa',522),('SCRE','Sección de Corte y Reconexión','Sección','Departamento de Gestión Operativa',523),
('DADM','Departamento Administrativo','Departamento','Dirección Administrativa y Financiera',301),('DFIN','Departamento Financiero','Departamento','Dirección Administrativa y Financiera',302),('DCP','Departamento de Contrataciones Públicas','Departamento','Dirección Administrativa y Financiera',303),
('SAFI','Sección de Activo Fijo','Sección','Departamento Administrativo',311),('STRA','Sección de Transportación','Sección','Departamento Administrativo',312),('DSGE','División de Servicios Generales','División','Departamento Administrativo',313),
('SSEG','Sección de Seguridad','Sección','División de Servicios Generales',314),('SMAY','Sección de Mayordomía','Sección','División de Servicios Generales',315),('SMRE','Sección de Mantenimiento y Reparación','Sección','División de Servicios Generales',316),('SARC','Sección de Archivo y Correspondencia','Sección','División de Servicios Generales',317),('SALS','Sección de Almacén y Suministro','Sección','División de Servicios Generales',318),
('SCON','Sección de Contabilidad','Sección','Departamento Financiero',321),('SPPT','Sección de Presupuesto','Sección','Departamento Financiero',322),('STES','Sección de Tesorería','Sección','Departamento Financiero',323),
('SPPC','Sección de Planeación y Preparación de Contrataciones','Sección','Departamento de Contrataciones Públicas',331),('SGCT','Sección de Gestión Contractual','Sección','Departamento de Contrataciones Públicas',332),
('DARS','Departamento de Aguas Residuales y Saneamiento','Departamento','Dirección Técnica',401),('DOMA','Departamento de Operación y Mantenimiento','Departamento','Dirección Técnica',402),('DPTA','Departamento de Producción y Tratamiento de Agua Potable','Departamento','Dirección Técnica',403),('DING','Departamento de Ingeniería','Departamento','Dirección Técnica',404),
('SOMR','Sección de Operación y Mantenimiento de Redes de Aguas Residuales','Sección','Departamento de Aguas Residuales y Saneamiento',411),('STAR','Sección de Tratamiento de Aguas Residuales','Sección','Departamento de Aguas Residuales y Saneamiento',412),('SCAR','Sección de Control de Calidad de Aguas Residuales','Sección','Departamento de Aguas Residuales y Saneamiento',413),
('SODA','Sección de Operación y Distribución de Agua Potable','Sección','Departamento de Operación y Mantenimiento',421),('SCRA','Sección de Catastro de Redes de Agua Potable','Sección','Departamento de Operación y Mantenimiento',422),('SELM','Sección de Electromecánica','Sección','Departamento de Operación y Mantenimiento',423),('SMRD','Sección de Mantenimiento de Redes','Sección','Departamento de Operación y Mantenimiento',424),('SOZP','Sección de Operación y Mantenimiento de Redes de Zonas Periféricas','Sección','Departamento de Operación y Mantenimiento',425),
('STAP','Sección de Tratamiento de Agua Potable','Sección','Departamento de Producción y Tratamiento de Agua Potable',431),('SLAP','Sección de Laboratorio de Agua Potable','Sección','Departamento de Producción y Tratamiento de Agua Potable',432),('SOBT','Sección de Obra de Toma','Sección','Departamento de Producción y Tratamiento de Agua Potable',433),('SCCA','Sección de Control y Calidad de Agua Potable','Sección','Departamento de Producción y Tratamiento de Agua Potable',434),
('SCNS','Sección de Construcción','Sección','Departamento de Ingeniería',441),('SDPO','Sección de Diseño y Presupuesto','Sección','Departamento de Ingeniería',442),('SFCO','Sección de Fiscalización y Control de Obras','Sección','Departamento de Ingeniería',443)
)
insert into public.organization_units(unit_code,unit_name,unit_type,sort_order)
select code,name,type_name,sort_order from units
on conflict(unit_name) do update set unit_code=excluded.unit_code,unit_type=excluded.unit_type,sort_order=excluded.sort_order,active=true;

with relations(child_name,parent_name) as (values
('Dirección de Comunicaciones','Dirección General'),('Dirección de Recursos Humanos','Dirección General'),('Dirección Administrativa y Financiera','Dirección General'),('Dirección Técnica','Dirección General'),('Dirección Comercial','Dirección General'),('Dirección de Planificación y Desarrollo','Dirección General'),
('Departamento de Tecnología de la Información y Comunicación (TIC)','Dirección General'),('Departamento de Control y Análisis de Operaciones','Dirección General'),('Departamento Jurídico','Dirección General'),('Oficina de Acceso a la Información','Dirección General'),
('División de Relaciones Públicas','Dirección de Comunicaciones'),('División de Participación Social y Ciudadana','Dirección de Comunicaciones'),('Sección de Prensa','División de Relaciones Públicas'),('Sección de Protocolo y Eventos','Dirección de Comunicaciones'),('Sección de Redes Sociales y Medios Digitales','Dirección de Comunicaciones'),
('Sección de Registro, Control y Nómina','Dirección de Recursos Humanos'),('Sección de Evaluación del Desempeño y Capacitaciones','Dirección de Recursos Humanos'),('Sección de Organización del Trabajo y Compensaciones','Dirección de Recursos Humanos'),
('Departamento de Desarrollo Institucional y Calidad en la Gestión','Dirección de Planificación y Desarrollo'),('Sección de Cooperación Internacional','Dirección de Planificación y Desarrollo'),('Departamento de Formulación, Monitoreo y Evaluación de Planes, Programas y Proyectos','Dirección de Planificación y Desarrollo'),
('Sección de Administración de Servicios TIC','Departamento de Tecnología de la Información y Comunicación (TIC)'),('Sección de Operaciones TIC','Departamento de Tecnología de la Información y Comunicación (TIC)'),
('Departamento de Gestión Comercial','Dirección Comercial'),('Departamento de Gestión Operativa','Dirección Comercial'),('Sección de Gestión de Cobros','Departamento de Gestión Comercial'),('Sección de Facturación','Departamento de Gestión Comercial'),('Sección de Atención al Cliente','Departamento de Gestión Comercial'),('Centros de Pagos Externos','Departamento de Gestión Comercial'),('Centros de Servicio al Cliente','Departamento de Gestión Comercial'),('Sección de Catastro de Usuarios','Departamento de Gestión Operativa'),('Sección de Micromedición','Departamento de Gestión Operativa'),('Sección de Corte y Reconexión','Departamento de Gestión Operativa'),
('Departamento Administrativo','Dirección Administrativa y Financiera'),('Departamento Financiero','Dirección Administrativa y Financiera'),('Departamento de Contrataciones Públicas','Dirección Administrativa y Financiera'),('Sección de Activo Fijo','Departamento Administrativo'),('Sección de Transportación','Departamento Administrativo'),('División de Servicios Generales','Departamento Administrativo'),('Sección de Seguridad','División de Servicios Generales'),('Sección de Mayordomía','División de Servicios Generales'),('Sección de Mantenimiento y Reparación','División de Servicios Generales'),('Sección de Archivo y Correspondencia','División de Servicios Generales'),('Sección de Almacén y Suministro','División de Servicios Generales'),('Sección de Contabilidad','Departamento Financiero'),('Sección de Presupuesto','Departamento Financiero'),('Sección de Tesorería','Departamento Financiero'),('Sección de Planeación y Preparación de Contrataciones','Departamento de Contrataciones Públicas'),('Sección de Gestión Contractual','Departamento de Contrataciones Públicas'),
('Departamento de Aguas Residuales y Saneamiento','Dirección Técnica'),('Departamento de Operación y Mantenimiento','Dirección Técnica'),('Departamento de Producción y Tratamiento de Agua Potable','Dirección Técnica'),('Departamento de Ingeniería','Dirección Técnica'),
('Sección de Operación y Mantenimiento de Redes de Aguas Residuales','Departamento de Aguas Residuales y Saneamiento'),('Sección de Tratamiento de Aguas Residuales','Departamento de Aguas Residuales y Saneamiento'),('Sección de Control de Calidad de Aguas Residuales','Departamento de Aguas Residuales y Saneamiento'),
('Sección de Operación y Distribución de Agua Potable','Departamento de Operación y Mantenimiento'),('Sección de Catastro de Redes de Agua Potable','Departamento de Operación y Mantenimiento'),('Sección de Electromecánica','Departamento de Operación y Mantenimiento'),('Sección de Mantenimiento de Redes','Departamento de Operación y Mantenimiento'),('Sección de Operación y Mantenimiento de Redes de Zonas Periféricas','Departamento de Operación y Mantenimiento'),
('Sección de Tratamiento de Agua Potable','Departamento de Producción y Tratamiento de Agua Potable'),('Sección de Laboratorio de Agua Potable','Departamento de Producción y Tratamiento de Agua Potable'),('Sección de Obra de Toma','Departamento de Producción y Tratamiento de Agua Potable'),('Sección de Control y Calidad de Agua Potable','Departamento de Producción y Tratamiento de Agua Potable'),
('Sección de Construcción','Departamento de Ingeniería'),('Sección de Diseño y Presupuesto','Departamento de Ingeniería'),('Sección de Fiscalización y Control de Obras','Departamento de Ingeniería')
)
update public.organization_units child set parent_id=parent.id
from relations r join public.organization_units parent on parent.unit_name=r.parent_name
where child.unit_name=r.child_name;
