"use client";
import {FormEvent,useEffect,useMemo,useRef,useState} from "react";

type Field={name:string;label:string;type?:string;required?:boolean;placeholder?:string;wide?:boolean};
type Position={id:string;occupational_group:string;family:string;position_name:string};
type Unit={id:string;parent_id:string|null;unit_name:string;unit_type:string;sort_order:number};
export type EmployeeProfileData={id:string;employee_code:string;full_name:string;document_number:string;birth_date:string|null;academic_level:string;blood_type:string;driver_license:string;cell_phone:string;landline_phone:string;home_address:string;hire_date:string|null;center_name:string;immediate_supervisor:string;direction_name:string;department_name:string;division_name:string;section_name:string;employment_status:string;payroll_status?:string;occupational_group:string;position_name:string;monthly_salary:number;benefits?:{type:string;amount:number;active:boolean}[]};
const identity:Field[]=[
 {name:"full_name",label:"Nombre y apellido",required:true,placeholder:"Nombre completo",wide:true},
 {name:"document_number",label:"Cédula",required:true,placeholder:"Solo números"},
 {name:"birth_date",label:"Fecha de nacimiento",type:"date"},
 {name:"academic_level",label:"Escolaridad",placeholder:"Nivel académico"},
 {name:"blood_type",label:"Tipo de sangre",placeholder:"Ej.: O+"},
 {name:"driver_license",label:"Licencia de conducir",placeholder:"Número de licencia"}
];
const contact:Field[]=[
 {name:"cell_phone",label:"Celular",type:"tel",placeholder:"(809) 000-0000"},
 {name:"landline_phone",label:"Teléfono",type:"tel",placeholder:"(809) 000-0000"},
 {name:"home_address",label:"Dirección donde vive",placeholder:"Calle, sector y municipio",wide:true}
];
const work:Field[]=[
 {name:"hire_date",label:"Fecha de entrada",type:"date",required:true},
 {name:"center_name",label:"Centro de servicio",placeholder:"Si aplica"},
 {name:"immediate_supervisor",label:"Superior inmediato",placeholder:"Nombre y cargo"}
];
const benefits=[["PRIMA_TRANSPORTE","Prima de transporte","Asignación recurrente para transporte"],["VIATICOS","Viáticos","Asignación por servicios fuera de la sede"],["HORAS_EXTRAS","Horas extras","Compensación por jornada extraordinaria"]] as const;

function FieldControl({field,initial}:{field:Field;initial?:EmployeeProfileData}){return <label className={field.wide?"profile-wide":""}><span>{field.label}{field.required&&<b> *</b>}</span><input name={field.name} type={field.type||"text"} required={field.required} placeholder={field.placeholder} defaultValue={String(initial?.[field.name as keyof EmployeeProfileData]??"")} inputMode={field.name==="document_number"?"numeric":undefined} pattern={field.name==="document_number"?"[0-9]{11}":undefined} maxLength={field.name==="document_number"?11:undefined}/>{field.name==="document_number"&&<small>11 dígitos, sin guiones.</small>}</label>}

export default function EmployeeProfileForm({initial,onSaved,onCancel}:{initial?:EmployeeProfileData;onSaved?:()=>void;onCancel?:()=>void}){
 const formRef=useRef<HTMLFormElement>(null);
 const [message,setMessage]=useState(""),[busy,setBusy]=useState(false),[enabled,setEnabled]=useState<Record<string,boolean>>({}),[positions,setPositions]=useState<Position[]>([]),[units,setUnits]=useState<Unit[]>([]),[group,setGroup]=useState(""),[directionId,setDirectionId]=useState(""),[departmentId,setDepartmentId]=useState(""),[divisionId,setDivisionId]=useState(""),[sectionId,setSectionId]=useState("");
 const activeBenefits=useMemo(()=>Object.values(enabled).filter(Boolean).length,[enabled]);
 const groupedPositions=useMemo(()=>positions.filter(position=>position.occupational_group===group).reduce<Record<string,Position[]>>((result,position)=>{(result[position.family]||=[]).push(position);return result},{}),[positions,group]);
 useEffect(()=>{fetch("/api/hr/positions",{cache:"no-store"}).then(response=>response.json()).then(data=>setPositions(Array.isArray(data.positions)?data.positions:[])).catch(()=>setPositions([]))},[]);
 useEffect(()=>{fetch("/api/organization",{cache:"no-store"}).then(response=>response.json()).then(data=>setUnits(Array.isArray(data.units)?data.units:[])).catch(()=>setUnits([]))},[]);
 useEffect(()=>{if(!initial)return;setGroup(initial.occupational_group||"");setEnabled(Object.fromEntries((initial.benefits||[]).filter(item=>item.active).map(item=>[item.type,true])))},[initial]);
 useEffect(()=>{if(!initial||!units.length)return;const find=(name:string)=>units.find(unit=>unit.unit_name===name)?.id||"";setDirectionId(find(initial.direction_name));setDepartmentId(find(initial.department_name));setDivisionId(find(initial.division_name));setSectionId(find(initial.section_name))},[initial,units]);
 useEffect(()=>{if(!initial||!formRef.current)return;const form=formRef.current;for(const [name,value] of Object.entries(initial)){const control=form.elements.namedItem(name) as HTMLInputElement|HTMLSelectElement|null;if(control&&name!=="benefits")control.value=String(name==="employment_status"?(initial.payroll_status||value||""):(value??""))}for(const benefit of initial.benefits||[]){const control=form.elements.namedItem(`amount_${benefit.type}`) as HTMLInputElement|null;if(control)control.value=String(benefit.amount??0)}},[initial,positions,units]);
 const directions=useMemo(()=>units.filter(unit=>unit.unit_type==="Dirección").sort((a,b)=>a.sort_order-b.sort_order),[units]);
 function descendants(parentId:string,type:string){if(!parentId)return[];const ids=new Set([parentId]);let changed=true;while(changed){changed=false;for(const unit of units)if(unit.parent_id&&ids.has(unit.parent_id)&&!ids.has(unit.id)&&unit.unit_type!=="Dirección"){ids.add(unit.id);changed=true}}return units.filter(unit=>unit.id!==parentId&&ids.has(unit.id)&&unit.unit_type===type).sort((a,b)=>a.sort_order-b.sort_order)}
 const departments=useMemo(()=>descendants(directionId,"Departamento"),[units,directionId]);
 const divisions=useMemo(()=>descendants(departmentId||directionId,"División"),[units,directionId,departmentId]);
 const sections=useMemo(()=>descendants(divisionId||departmentId||directionId,"Sección"),[units,directionId,departmentId,divisionId]);
 const unitName=(id:string)=>units.find(unit=>unit.id===id)?.unit_name||"";
 async function submit(e:FormEvent<HTMLFormElement>){
  e.preventDefault();setBusy(true);setMessage("");const form=e.currentTarget;const f=new FormData(form);const data:Record<string,unknown>=Object.fromEntries(f);
  data.id=initial?.id||"";data.employee_code=initial?.employee_code||"";data.monthly_salary=Number(f.get("monthly_salary")||0);data.benefits=benefits.filter(([key])=>enabled[key]).map(([key])=>({type:key,amount:Number(f.get(`amount_${key}`)||0),active:true}));
  try{const r=await fetch("/api/hr/employee-profile",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const d=await r.json();setMessage(r.ok?`Empleado ${initial?"actualizado":"guardado"} correctamente con el código ${d.employee_code}.`:d.error||"No fue posible guardar la ficha.");if(r.ok){if(initial){onSaved?.()}else{form.reset();setEnabled({});setGroup("");setDirectionId("");setDepartmentId("");setDivisionId("");setSectionId("");window.scrollTo({top:0,behavior:"smooth"})}}}catch{setMessage("No fue posible conectar con el registro de empleados.")}finally{setBusy(false)}
 }
 return <section className="employee-profile-page">
  <div className="direction-strip"><strong>DIRECCIÓN RESPONSABLE</strong><span>Dirección de Recursos Humanos · Expediente maestro</span></div>
  <header className="profile-hero"><div><span className="eyebrow">REGISTRO DE PERSONAL</span><h2>{initial?`Editar ficha de ${initial.full_name}`:"Nueva ficha de empleado"}</h2><p>Centraliza la identificación, ubicación institucional, compensación y beneficios del colaborador.</p></div><aside><i>{initial?"Empleado registrado":"Automático"}</i><strong>Código de empleado</strong><small>{initial?.employee_code||"Se asignará al guardar la ficha."}</small></aside></header>
  {message&&<div className={`profile-message ${message.includes("correctamente")?"success":"error"}`}>{message}</div>}
  <form ref={formRef} className="employee-profile-form" onSubmit={submit} key={initial?.id||"new"}>
   <section className="profile-card"><header><span>01</span><div><h3>Identificación personal</h3><p>Datos básicos y documentos del empleado.</p></div></header><div className="profile-grid">{identity.map(field=><FieldControl key={field.name} field={field}/>)}</div></section>
   <section className="profile-card"><header><span>02</span><div><h3>Contacto y residencia</h3><p>Información privada para el expediente de Recursos Humanos.</p></div></header><div className="profile-grid">{contact.map(field=><FieldControl key={field.name} field={field}/>)}</div></section>
   <section className="profile-card hierarchy-card"><header><span>03</span><div><h3>Asignación institucional</h3><p>Estructura jerárquica y lugar de trabajo.</p></div><strong>Selección dirigida</strong></header><div className="hierarchy-notice"><i>1</i><span>Seleccione la dirección. Los niveles siguientes mostrarán únicamente sus dependencias válidas.</span></div><div className="profile-grid"><label><span>Dirección <b>*</b></span><select value={directionId} onChange={event=>{setDirectionId(event.target.value);setDepartmentId("");setDivisionId("");setSectionId("")}} required><option value="">Seleccionar dirección</option>{directions.map(unit=><option value={unit.id} key={unit.id}>{unit.unit_name}</option>)}</select><input type="hidden" name="direction_name" value={unitName(directionId)}/></label><label><span>Departamento</span><select value={departmentId} onChange={event=>{setDepartmentId(event.target.value);setDivisionId("");setSectionId("")}} disabled={!directionId||departments.length===0}><option value="">{departments.length?"Seleccionar departamento":"No aplica"}</option>{departments.map(unit=><option value={unit.id} key={unit.id}>{unit.unit_name}</option>)}</select><input type="hidden" name="department_name" value={unitName(departmentId)}/></label><label><span>División</span><select value={divisionId} onChange={event=>{setDivisionId(event.target.value);setSectionId("")}} disabled={!directionId||divisions.length===0}><option value="">{divisions.length?"Seleccionar división":"No aplica"}</option>{divisions.map(unit=><option value={unit.id} key={unit.id}>{unit.unit_name}</option>)}</select><input type="hidden" name="division_name" value={unitName(divisionId)}/></label><label><span>Sección</span><select value={sectionId} onChange={event=>setSectionId(event.target.value)} disabled={!directionId||sections.length===0}><option value="">{sections.length?"Seleccionar sección":"No aplica"}</option>{sections.map(unit=><option value={unit.id} key={unit.id}>{unit.unit_name}</option>)}</select><input type="hidden" name="section_name" value={unitName(sectionId)}/></label>{work.map(field=><FieldControl key={field.name} field={field}/>)}</div><div className="hierarchy-path"><span>Ubicación seleccionada</span><strong>{[unitName(directionId),unitName(departmentId),unitName(divisionId),unitName(sectionId)].filter(Boolean).join(" → ")||"Pendiente de selección"}</strong></div></section>
   <section className="profile-card"><header><span>04</span><div><h3>Clasificación laboral</h3><p>El cargo se selecciona desde el manual institucional según su grupo ocupacional.</p></div></header><div className="profile-grid"><label><span>Estatus laboral <b>*</b></span><select name="employment_status" required><option value="">Seleccionar</option>{["Fijo","Carrera Administrativa","Temporal","Interino","Estatuto Simplificado"].map(value=><option key={value}>{value}</option>)}</select></label><label><span>Grupo ocupacional <b>*</b></span><select name="occupational_group" value={group} onChange={event=>setGroup(event.target.value)} required><option value="">Seleccionar grupo</option>{["I","II","III","IV","V"].map(value=><option key={value}>{value}</option>)}</select></label><label className="profile-wide"><span>Cargo del manual <b>*</b></span><select name="position_name" required disabled={!group}><option value="">{group?"Seleccionar cargo":"Seleccione primero el grupo ocupacional"}</option>{Object.entries(groupedPositions).map(([family,items])=><optgroup label={family} key={family}>{items.map(position=><option key={position.id} value={position.position_name}>{position.position_name}</option>)}</optgroup>)}</select><small>{group&&positions.length===0?"El catálogo estará disponible cuando finalice la migración de Supabase.":`${positions.filter(position=>position.occupational_group===group).length} cargos disponibles en el grupo ${group||"seleccionado"}.`}</small></label><label><span>Salario mensual <b>*</b></span><div className="money-input"><i>RD$</i><input name="monthly_salary" type="number" min="0" step="0.01" required placeholder="0.00"/></div></label></div></section>
   <section className="profile-card benefits-card"><header><span>05</span><div><h3>Beneficios adicionales</h3><p>Active únicamente los beneficios autorizados para este empleado.</p></div><strong>{activeBenefits} activos</strong></header><div className="profile-benefits">{benefits.map(([key,label,description])=><article className={enabled[key]?"enabled":""} key={key}><label><input type="checkbox" checked={Boolean(enabled[key])} onChange={event=>setEnabled(current=>({...current,[key]:event.target.checked}))}/><i/><span><b>{label}</b><small>{description}</small></span></label><div className="money-input"><i>RD$</i><input name={`amount_${key}`} type="number" min="0" step="0.01" disabled={!enabled[key]} required={enabled[key]} placeholder="0.00"/></div></article>)}</div></section>
   <footer className="profile-actions"><div><strong>{initial?"Actualización controlada":"Campos obligatorios"}</strong><span>{initial?"Los cambios quedarán registrados en el histórico del empleado.":"Los campos marcados con * deben completarse antes de guardar."}</span></div>{initial&&<button type="button" className="outline" onClick={onCancel}>Cancelar edición</button>}<button className="primary" disabled={busy}>{busy?"Guardando ficha…":initial?"Guardar cambios":"Guardar ficha de empleado"}</button></footer>
  </form>
 </section>
}
