"use client";
import {useCallback,useEffect,useMemo,useState} from "react";

type Summary={permissions:number;vacations:number;warnings:number;pending:number;approved_absence_days:number};
type Row={employee_id:string;employee_code:string;full_name:string;position_name:string;direction_name:string;department_name:string;permission_count:number;medical_license_count:number;consecutive_licenses:number;vacation_count:number;warning_count:number;pending_count:number;approved_absence_days:number;last_request_date:string;risk_level:"ALTO"|"MEDIO"|"BAJO";recommendation:string};
const empty:Summary={permissions:0,vacations:0,warnings:0,pending:0,approved_absence_days:0};

export default function HrCaseAnalytics(){
 const [year,setYear]=useState("ALL"),[summary,setSummary]=useState<Summary>(empty),[rows,setRows]=useState<Row[]>([]),[query,setQuery]=useState(""),[risk,setRisk]=useState("TODOS"),[busy,setBusy]=useState(true),[message,setMessage]=useState("");
 const load=useCallback(async()=>{setBusy(true);setMessage("");try{const response=await fetch(`/api/hr/case-analytics?year=${year}`,{cache:"no-store"}),data=await response.json();if(!response.ok)throw new Error(data.error||"No fue posible cargar los indicadores.");setSummary(data.summary||empty);setRows(Array.isArray(data.employees)?data.employees:[])}catch(error){setMessage(error instanceof Error?error.message:"No fue posible cargar los indicadores.");setRows([])}finally{setBusy(false)}},[year]);
 useEffect(()=>{load()},[load]);
 const filtered=useMemo(()=>rows.filter(row=>(risk==="TODOS"||row.risk_level===risk)&&`${row.full_name} ${row.employee_code} ${row.direction_name} ${row.department_name}`.toLowerCase().includes(query.toLowerCase())),[rows,query,risk]);
 const high=rows.filter(row=>row.risk_level==="ALTO").length,medium=rows.filter(row=>row.risk_level==="MEDIO").length;
 return <section className="employee-registry-panel hr-analytics">
  <div className="direction-strip"><strong>ANÁLISIS PARA TOMA DE DECISIONES</strong><span>Dirección de Recursos Humanos · Indicadores de novedades</span></div>
  <div className="employee-registry-head"><div><span className="eyebrow">KPIS DE GESTIÓN HUMANA</span><h2>Permisos, licencias, vacaciones y amonestaciones</h2><p>Alertas de recurrencia para seguimiento preventivo y decisiones documentadas.</p></div><label>Período<select value={year} onChange={event=>setYear(event.target.value)}><option value="ALL">Todos los años</option>{Array.from({length:10},(_,index)=>2026+index).map(value=><option key={value}>{value}</option>)}</select></label></div>
  <div className="technical-kpis"><article><span>PERMISOS SOLICITADOS</span><strong>{summary.permissions}</strong></article><article><span>VACACIONES SOLICITADAS</span><strong>{summary.vacations}</strong></article><article><span>AMONESTACIONES</span><strong>{summary.warnings}</strong></article><article><span>DECISIONES PENDIENTES</span><strong>{summary.pending}</strong></article></div>
  <div className="analytics-alerts"><article className="risk-high"><span>REVISIÓN PRIORITARIA</span><strong>{high}</strong><small>Empleados con nivel alto</small></article><article className="risk-medium"><span>SEGUIMIENTO PREVENTIVO</span><strong>{medium}</strong><small>Empleados con nivel medio</small></article><article><span>DÍAS DE AUSENCIA APROBADOS</span><strong>{summary.approved_absence_days}</strong><small>Permisos y vacaciones</small></article></div>
  <div className="analytics-policy"><strong>Criterios orientativos</strong><span>Alto: 5 permisos, 3 licencias consecutivas o 3 amonestaciones. Medio: 3 permisos, 2 licencias consecutivas, 3 solicitudes de vacaciones o 2 amonestaciones. Una licencia se considera consecutiva cuando inicia hasta 7 días después de la anterior.</span></div>
  {message&&<div className="form-message">{message}</div>}
  <div className="technical-card"><div className="users-card-head"><div><h2>Empleados para seguimiento</h2><p>Las alertas no sustituyen la investigación, el debido proceso ni la validación documental.</p></div><div className="analytics-filters"><select value={risk} onChange={event=>setRisk(event.target.value)}><option value="TODOS">Todos los niveles</option><option>ALTO</option><option>MEDIO</option><option>BAJO</option></select><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar empleado o área"/></div></div>
   {busy?<div className="users-empty">Calculando indicadores…</div>:!filtered.length?<div className="technical-empty"><strong>No existen empleados con registros en este período</strong><span>Seleccione otro período o revise los módulos de novedades.</span></div>:<div className="users-table-wrap"><table className="employee-registry-table analytics-table"><thead><tr><th>EMPLEADO / ÁREA</th><th>PERMISOS</th><th>LICENCIAS</th><th>VACACIONES</th><th>AMONESTACIONES</th><th>AUSENCIA / PENDIENTES</th><th>NIVEL</th><th>MEDIDA SUGERIDA</th></tr></thead><tbody>{filtered.map(row=><tr key={row.employee_id}><td><strong>{row.full_name}</strong><small>{row.employee_code} · {row.position_name}<br/>{row.department_name||row.direction_name}</small></td><td><strong>{row.permission_count}</strong></td><td><strong>{row.medical_license_count}</strong><small>{row.consecutive_licenses} consecutivas</small></td><td><strong>{row.vacation_count}</strong></td><td><strong>{row.warning_count}</strong></td><td><strong>{row.approved_absence_days} días</strong><small>{row.pending_count} decisiones pendientes</small></td><td><span className={`analytics-risk risk-${row.risk_level.toLowerCase()}`}>{row.risk_level}</span></td><td><strong>{row.recommendation}</strong><small>Última solicitud: {row.last_request_date?new Date(`${row.last_request_date}T12:00:00`).toLocaleDateString("es-DO"):"—"}</small></td></tr>)}</tbody></table></div>}
  </div>
  <style jsx>{`.analytics-alerts{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.analytics-alerts article{padding:16px;border:1px solid #dbe5eb;border-radius:10px;background:#fff}.analytics-alerts span,.analytics-alerts strong,.analytics-alerts small{display:block}.analytics-alerts span{font-size:8px;font-weight:850;color:#60798b}.analytics-alerts strong{font-size:25px;margin:5px 0}.analytics-alerts small{font-size:8px;color:#8293a0}.analytics-alerts .risk-high{background:#fff1f2;border-color:#edc8cc}.analytics-alerts .risk-medium{background:#fff8e8;border-color:#efdfb4}.analytics-policy{display:grid;grid-template-columns:170px 1fr;gap:12px;padding:13px 16px;border-radius:9px;background:#eaf3f8;color:#426276;font-size:9px;line-height:1.5}.analytics-filters{display:flex;gap:8px}.analytics-filters select,.analytics-filters input{height:36px;border:1px solid #d7e2e8;border-radius:7px;background:#fff;padding:0 10px}.analytics-table{min-width:1250px}.analytics-table td:not(:first-child):not(:last-child){text-align:center}.analytics-risk{display:inline-block;padding:5px 9px;border-radius:14px;font-size:8px;font-weight:900}.risk-alto{background:#f9dfe2;color:#ad2635}.risk-medio{background:#fff0c9;color:#91620b}.risk-bajo{background:#e4f3ed;color:#26735b}@media(max-width:800px){.analytics-alerts{grid-template-columns:1fr}.analytics-policy{grid-template-columns:1fr}.analytics-filters{flex-direction:column}}`}</style>
 </section>;
}
