"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
type Line={id:string;employee_code:string;document_number:string;employee_name:string;position_name:string;gross_salary:number;isr:number;insurance:number;employee_pension:number;employee_sfs:number;employer_pension:number;employer_sfs:number;employer_labor_risk:number;other_deductions:number;total_deductions:number;net_amount:number};
type Account={code:string;name:string;parent_code:string|null};
const labels:Record<string,string>={NOMINA:"Nómina mensual",PRIMA_TRANSPORTE:"Prima de transporte",VIATICOS:"Viáticos",HORAS_EXTRAS:"Horas extras"};
const money=(n:number)=>new Intl.NumberFormat("es-DO",{style:"currency",currency:"DOP"}).format(Number(n||0));
export default function PayrollProcessing({type}:{type:string}){
 const [year,setYear]=useState(2026),[month,setMonth]=useState(6),[lines,setLines]=useState<Line[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[account,setAccount]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const load=async()=>{setBusy(true);const r=await fetch(`/api/hr/payroll-processing?year=${year}&month=${month}&type=${type}`,{cache:"no-store"});const d=await r.json();setLines(Array.isArray(d.lines)?d.lines:[]);setAccounts(Array.isArray(d.accounts)?d.accounts:[]);setAccount(d.batch?.account_code||"");if(!r.ok)setMessage(d.error);setBusy(false)};
 useEffect(()=>{load()},[year,month,type]);
 const total=useMemo(()=>lines.reduce((s,l)=>s+Number(l.net_amount),0),[lines]);
 async function generate(){setBusy(true);setMessage("");const r=await fetch("/api/hr/payroll-processing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({year,month,type,account_code:account})});const d=await r.json();setMessage(r.ok?`${labels[type]} generada correctamente.`:d.error);if(r.ok)await load();else setBusy(false)}
 async function editIsr(line:Line){const value=prompt("ISR manual para la prima de transporte",String(line.isr));if(value===null)return;await fetch("/api/hr/payroll-processing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"manual-isr",line_id:line.id,isr:Number(value)})});load()}
 function exportCsv(){const head=["Código/Cédula","Empleado/Cargo","Sueldo Bruto","ISR","Seguro","Empleado S. Social","Empleado SFS","Empleador SFS","Empleador S. Social","Riesgo Lab.","Otros Desc.","Total Desc.","Neto"];const rows=lines.map(l=>[`${l.employee_code}/${l.document_number}`,`${l.employee_name}/${l.position_name}`,l.gross_salary,l.isr,l.insurance,l.employee_pension,l.employee_sfs,l.employer_sfs,l.employer_pension,l.employer_labor_risk,l.other_deductions,l.total_deductions,l.net_amount]);const csv=[head,...rows].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff",csv],{type:"text/csv"}));a.download=`${type.toLowerCase()}-${year}-${month}.csv`;a.click()}
 return <section className="payroll-panel"><div className="direction-strip"><strong>DIRECCIÓN RESPONSABLE</strong><span>Dirección de Recursos Humanos · Registro, Control y Nómina</span></div><div className="payroll-head"><div><span className="eyebrow">ELABORACIÓN Y REPORTE</span><h2>{labels[type]}</h2><p>Los aportes se calculan con parámetros vigentes y quedan guardados en cada registro.</p></div><div><select value={year} onChange={e=>setYear(+e.target.value)}>{[2026,2027,2028,2029,2030].map(y=><option key={y}>{y}</option>)}</select><select value={month} onChange={e=>setMonth(+e.target.value)}>{Array.from({length:12},(_,i)=><option value={i+1} key={i}>{new Date(2026,i,1).toLocaleDateString("es-DO",{month:"long"})}</option>)}</select></div></div><div className="payroll-import"><label>Cuenta presupuestaria<select value={account} onChange={e=>setAccount(e.target.value)}><option value="">Seleccionar cuenta</option>{accounts.filter(a=>a.parent_code).map(a=><option key={a.code} value={a.code}>{a.code} · {a.name}</option>)}</select></label><button className="primary" disabled={busy} onClick={generate}>{busy?"Procesando…":`Generar ${labels[type]}`}</button><button className="outline" disabled={!lines.length} onClick={exportCsv}>Exportar reporte</button></div>{message&&<div className="form-message">{message}</div>}<div className="payroll-kpis"><article><span>EMPLEADOS</span><strong>{lines.length}</strong></article><article><span>SUELDO BRUTO</span><strong>{money(lines.reduce((s,l)=>s+Number(l.gross_salary),0))}</strong></article><article><span>TOTAL DESCUENTOS</span><strong>{money(lines.reduce((s,l)=>s+Number(l.total_deductions),0))}</strong></article><article><span>NETO</span><strong>{money(total)}</strong></article></div><div className="users-table-wrap"><table className="payroll-table"><thead><tr><th>CÓDIGO/CÉDULA</th><th>EMPLEADO/CARGO</th><th>SUELDO BRUTO</th><th>ISR</th><th>SEGURO</th><th>EMPLEADO<br/>S. SOCIAL / SFS</th><th>EMPLEADOR<br/>SFS / S. SOCIAL / RIESGO</th><th>OTROS DESC.</th><th>TOTAL DESC.</th><th>NETO</th></tr></thead><tbody>{lines.map(l=><tr key={l.id}><td>{l.employee_code}<small>{l.document_number}</small></td><td><strong>{l.employee_name}</strong><small>{l.position_name}</small></td><td>{money(l.gross_salary)}</td><td>{type==="PRIMA_TRANSPORTE"?<button className="row-action" onClick={()=>editIsr(l)}>{money(l.isr)}</button>:money(l.isr)}</td><td>{money(l.insurance)}</td><td>{money(l.employee_pension)}<small>SFS: {money(l.employee_sfs)}</small></td><td>{money(l.employer_sfs)}<small>SS: {money(l.employer_pension)} · RL: {money(l.employer_labor_risk)}</small></td><td>{money(l.other_deductions)}</td><td>{money(l.total_deductions)}</td><td><strong>{money(l.net_amount)}</strong></td></tr>)}{!busy&&!lines.length&&<tr><td colSpan={10}>No existe una nómina generada para este período.</td></tr>}</tbody></table></div></section>
}
