"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
type Employee={id:string;employee_code:string;document_number:string;full_name:string;position_name:string;direction_name:string;department_name:string;division_name:string;section_name:string;monthly_salary:number;immediate_supervisor?:string};
type PersonnelActionRecord={id:string;action_number:number;employee_id:string;employee_code:string;full_name:string;action_type:string;effective_date:string;status:string;created_at:string};
const actions=[['APERTURA_CONCURSO','APERTURA DE CONCURSO'],['LICENCIA_ENFERMEDAD','LICENCIA POR ENFERMEDAD'],['PRORROGA_CONTRATO','PRÓRROGA DE CONTRATO'],['AUMENTO_SUELDO','AUMENTO DE SUELDO'],['LICENCIA_EMBARAZO','LICENCIA POR EMBARAZO'],['DESPIDO','DESPIDO'],['ASCENSO','ASCENSO'],['COMPENSACION','COMPENSACIÓN'],['ABANDONO_TRABAJO','ABANDONO DEL TRABAJO'],['INTERINAJE','INTERINAJE'],['REINGRESO_TRABAJO','REINGRESO AL TRABAJO'],['RENUNCIA','RENUNCIA'],['VACACIONES','VACACIONES'],['NOMBRAMIENTO_REGULAR','NOMBRAMIENTO REGULAR'],['TRASLADO','TRASLADO'],['LICENCIA_ESTUDIOS','LICENCIA POR ESTUDIOS'],['NOMBRAMIENTO_CONTRATO','NOMBRAMIENTO POR CONTRATO'],['OTROS','OTROS'],['LICENCIA_SIN_SUELDO','LICENCIA SIN SUELDO'],['RESCISION_CONTRATO','RESCISIÓN DE CONTRATO']] as const;
const stateFields=[['direction','Dirección'],['department','Departamento'],['division','División'],['section','Sección'],['position','Cargo'],['salary','Sueldo RD$']] as const;
const money=(value:unknown)=>Number(value||0).toLocaleString('es-DO',{minimumFractionDigits:2,maximumFractionDigits:2});

export default function PersonnelAction({canApprove=false}:{canApprove?:boolean}){
 const [employees,setEmployees]=useState<Employee[]>([]),[items,setItems]=useState<PersonnelActionRecord[]>([]),[selected,setSelected]=useState(''),[action,setAction]=useState(''),[message,setMessage]=useState(''),[saved,setSaved]=useState(false);
 const employee=useMemo(()=>employees.find(item=>item.id===selected),[employees,selected]);
 const loadActions=()=>fetch('/api/hr/personnel-actions',{cache:'no-store'}).then(response=>response.json()).then(data=>setItems(Array.isArray(data.items)?data.items:[]));
 useEffect(()=>{fetch('/api/hr/employees',{cache:'no-store'}).then(response=>response.json()).then(data=>setEmployees(Array.isArray(data.employees)?data.employees:[]));loadActions()},[]);
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!employee||!action)return;const form=new FormData(event.currentTarget);const proposed_state=Object.fromEntries(stateFields.map(([key])=>[key,form.get(`proposed_${key}`)]));const body={employee_id:employee.id,effective_date:form.get('effective_date'),action_type:action,other_action:form.get('other_action'),proposed_state,observations:form.get('observations'),recommendation:form.get('recommendation'),immediate_supervisor:form.get('immediate_supervisor'),department_manager:form.get('department_manager'),payroll_officer:form.get('payroll_officer'),general_director:form.get('general_director')};const response=await fetch('/api/hr/personnel-actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();setMessage(response.ok?'Acción registrada y pendiente de aprobación.':data.error);setSaved(response.ok);if(response.ok)await loadActions()}
 async function approve(item:PersonnelActionRecord){const response=await fetch('/api/hr/personnel-actions',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id})});const data=await response.json();setMessage(response.ok?'Acción aprobada y ficha del empleado actualizada.':data.error);if(response.ok){await loadActions();const employeesResponse=await fetch('/api/hr/employees',{cache:'no-store'});const employeesData=await employeesResponse.json();setEmployees(Array.isArray(employeesData.employees)?employeesData.employees:[])}}
 const present:Record<string,unknown>={direction:employee?.direction_name,department:employee?.department_name,division:employee?.division_name,section:employee?.section_name,position:employee?.position_name,salary:employee?.monthly_salary};
 return <section className="personnel-action-module">
  <div className="no-print direction-strip"><strong>DIRECCIÓN RESPONSABLE</strong><span>Dirección de Recursos Humanos · Acción de personal</span></div>
  <div className="no-print personnel-action-controls"><label>Empleado<select value={selected} onChange={event=>{setSelected(event.target.value);setSaved(false)}} required><option value="">Seleccionar empleado</option>{employees.map(item=><option key={item.id} value={item.id}>{item.employee_code} · {item.full_name}</option>)}</select></label><span>Complete el estado propuesto, registre el documento y luego imprímalo.</span></div>
  <form onSubmit={save}><article className="personnel-action-sheet">
   <header className="personnel-document-header"><div className="personnel-logo"><img src="/logo-coraamoca-oficial.jpg" alt="Logo oficial de CORAAMOCA"/></div><div className="personnel-heading"><span>FORMULARIO OFICIAL DE RECURSOS HUMANOS</span><h1>CORPORACIÓN DEL ACUEDUCTO Y ALCANTARILLADO DE MOCA</h1><strong>(CORAAMOCA)</strong><h2>ACCIÓN DE PERSONAL</h2></div></header>
   <div className="action-identification"><label>Nombre: <b>{employee?.full_name||''}</b></label><label>Codif. No.: <b>{employee?.employee_code||''}</b></label><label>Cédula No.: <b>{employee?.document_number||''}</b></label><label>Efectivo a partir de: <input name="effective_date" type="date" required/></label></div>
   <div className="state-columns"><section><h3>ESTADO PRESENTE</h3>{stateFields.map(([key,label])=><label key={key}>{label}<b>{key==='salary'?money(present[key]):String(present[key]||'')}</b></label>)}</section><section><h3>ESTADO QUE SE PROPONE</h3>{stateFields.map(([key,label])=><label key={key}>{label}<input name={`proposed_${key}`} type={key==='salary'?'number':'text'} step={key==='salary'?'0.01':undefined}/></label>)}</section></div>
   <h3 className="action-title">A C C I Ó N</h3><div className="action-options">{actions.map(([key,label])=><label key={key}><input type="radio" name="action_type" value={key} checked={action===key} onChange={()=>setAction(key)} required/><i/>{label}{key==='OTROS'&&<input name="other_action" className="other-action"/>}</label>)}</div>
   <label className="action-notes">Observaciones:<textarea name="observations" rows={3}/></label>
   <div className="action-approvals"><section><label>Recomendación<textarea name="recommendation" rows={2}/></label><div><label><input name="recommendation_date" type="date"/>Fecha</label><label><input name="immediate_supervisor" defaultValue={employee?.immediate_supervisor||''}/>Superior Inmediato</label><label><input name="department_date" type="date"/>Fecha</label><label><input name="department_manager"/>Enc. Departamento</label></div></section><section><h4>Visto Bueno</h4><div><label><input name="payroll_date" type="date"/>Fecha</label><label><input name="payroll_officer"/>Enc. Registro Control y Nómina</label><label><input name="director_date" type="date"/>Fecha</label><label><input name="general_director"/>Director General</label></div></section></div>
  </article><div className="no-print modal-actions">{message&&<span className="form-message">{message}</span>}<button className="primary" disabled={!employee||!action}>Guardar acción</button><button type="button" className="outline" disabled={!saved} onClick={()=>window.print()}>Imprimir documento</button></div></form>
  <div className="no-print pending-actions"><div><span>ACCIONES PENDIENTES</span><strong>{items.filter(item=>item.status==='BORRADOR').length}</strong></div>{items.filter(item=>item.status==='BORRADOR').slice(0,8).map(item=><article key={item.id}><div><strong>No. {item.action_number} · {item.full_name}</strong><span>{item.action_type.replaceAll('_',' ')} · Efectiva {new Date(item.effective_date).toLocaleDateString('es-DO')}</span></div>{canApprove?<button className="primary" onClick={()=>approve(item)}>Aprobar y aplicar</button>:<b>Pendiente de aprobación</b>}</article>)}</div>
  <style jsx global>{`
   .personnel-action-sheet{box-sizing:border-box!important;width:8.5in!important;height:11in!important;min-height:11in!important;max-height:11in!important}
   @media print{
    @page{size:letter portrait;margin:0}
    html,body{width:8.5in!important;height:11in!important;margin:0!important;padding:0!important;background:#fff!important}
    .personnel-action-sheet{position:absolute!important;inset:0!important;width:8.5in!important;height:11in!important;min-height:11in!important;max-height:11in!important;margin:0!important;border-radius:0!important;overflow:hidden!important;break-inside:avoid!important;page-break-inside:avoid!important;print-color-adjust:exact!important;-webkit-print-color-adjust:exact!important}
   }
  `}</style>
 </section>
}
