"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
type Employee={id:string;employee_code:string;document_number?:string;full_name:string;position_name:string};
type Rate={id:string;category:string;daily_amount:number};
type Item={id:string;request_number:number;employee_name:string;employee_code:string;position_name:string;destination:string;departure_at:string;return_at:string;days:number;daily_rate:number;transport_amount:number;toll_amount:number;total_amount:number;status:string;category:string;purpose:string;advance_warning:boolean};
const money=(n:number)=>new Intl.NumberFormat("es-DO",{style:"currency",currency:"DOP"}).format(Number(n||0));
const initial={employee_id:"",rate_id:"",destination:"",purpose:"",departure_at:"",return_at:"",transport_mode:"INSTITUCIONAL",transport_amount:0,toll_amount:0,support_url:"",observations:""};
export default function TravelAllowanceManagement(){
 const [year,setYear]=useState(2026),[employees,setEmployees]=useState<Employee[]>([]),[employeeSearch,setEmployeeSearch]=useState(""),[rates,setRates]=useState<Rate[]>([]),[items,setItems]=useState<Item[]>([]),[form,setForm]=useState({...initial}),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const load=async()=>{setBusy(true);const [vr,er]=await Promise.all([fetch(`/api/hr/travel-allowances?year=${year}`,{cache:"no-store"}),fetch("/api/hr/employees",{cache:"no-store"})]);const [v,e]=await Promise.all([vr.json(),er.json()]);setRates(Array.isArray(v.rates)?v.rates:[]);setItems(Array.isArray(v.items)?v.items:[]);setEmployees(Array.isArray(e.employees)?e.employees.filter((x:{active?:boolean})=>x.active!==false):[]);if(!vr.ok)setMessage(v.error||"No fue posible consultar los viáticos.");setBusy(false)};
 useEffect(()=>{load()},[year]);
 const selectedRate=useMemo(()=>rates.find(r=>r.id===form.rate_id),[rates,form.rate_id]);
 const filteredEmployees=useMemo(()=>{const term=employeeSearch.trim().normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();if(!term)return employees;return employees.filter(x=>[x.employee_code,x.document_number,x.full_name,x.position_name].filter(Boolean).join(" ").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().includes(term))},[employees,employeeSearch]);
 const preview=useMemo(()=>{if(!form.departure_at||!form.return_at||!selectedRate)return 0;const hours=(+new Date(form.return_at)-+new Date(form.departure_at))/36e5;return Math.max(1,Math.ceil(hours/24))*Number(selectedRate.daily_amount)+Number(form.transport_amount)+Number(form.toll_amount)},[form,selectedRate]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");const r=await fetch("/api/hr/travel-allowances",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();setMessage(r.ok?`Solicitud de viáticos núm. ${d.request_number} registrada.`:d.error);if(r.ok){setForm({...initial});await load()}else setBusy(false)}
 async function transition(id:string,status:string){const notes=status==="RECHAZADA"?prompt("Indique el motivo del rechazo:",""):"";if(status==="RECHAZADA"&&!notes)return;const r=await fetch("/api/hr/travel-allowances",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status,notes})});const d=await r.json();setMessage(r.ok?"Estado actualizado.":d.error);if(r.ok)load()}
 return <section className="travel-panel"><div className="direction-strip"><strong>DIRECCIÓN RESPONSABLE</strong><span>Recursos Humanos · Viáticos dentro del país · Cuenta 2.2.3.1.01</span></div><div className="payroll-head"><div><span className="eyebrow">RESOLUCIÓN MAP NÚM. 173-2025</span><h2>Gestión de viáticos</h2><p>Solicitudes, tarifas vigentes, transporte, aprobación, pago y soportes de la comisión.</p></div><select value={year} onChange={e=>setYear(+e.target.value)}>{[2025,2026,2027,2028].map(y=><option key={y}>{y}</option>)}</select></div>
 <form className="travel-form" onSubmit={submit}><h3>Nueva solicitud</h3><label>Buscar empleado<input type="search" value={employeeSearch} onChange={e=>setEmployeeSearch(e.target.value)} placeholder="Código, cédula, nombre o cargo" autoComplete="off"/><small>{employeeSearch?`${filteredEmployees.length} coincidencia(s) encontrada(s)`:"Escriba para reducir la lista"}</small></label><label>Empleado<select required value={form.employee_id} onChange={e=>setForm({...form,employee_id:e.target.value})}><option value="">{filteredEmployees.length?"Seleccione":"Sin coincidencias"}</option>{filteredEmployees.map(x=><option key={x.id} value={x.id}>{x.employee_code} · {x.full_name} · {x.position_name}</option>)}</select></label><label>Categoría y tarifa<select required value={form.rate_id} onChange={e=>setForm({...form,rate_id:e.target.value})}><option value="">Seleccione</option>{rates.map(x=><option key={x.id} value={x.id}>{x.category} · {money(x.daily_amount)} diarios</option>)}</select></label><label>Destino<input required value={form.destination} onChange={e=>setForm({...form,destination:e.target.value})}/></label><label>Motivo de la comisión<textarea required value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value})}/></label><label>Salida<input required type="datetime-local" value={form.departure_at} onChange={e=>setForm({...form,departure_at:e.target.value})}/></label><label>Regreso<input required type="datetime-local" value={form.return_at} onChange={e=>setForm({...form,return_at:e.target.value})}/></label><label>Transporte<select value={form.transport_mode} onChange={e=>setForm({...form,transport_mode:e.target.value})}><option value="INSTITUCIONAL">Vehículo institucional</option><option value="PROPIO">Vehículo propio autorizado</option><option value="PUBLICO">Transporte público</option></select></label><label>Pasaje o combustible RD$<input type="number" min="0" step="0.01" value={form.transport_amount} onChange={e=>setForm({...form,transport_amount:+e.target.value})}/></label><label>Peajes RD$<input type="number" min="0" step="0.01" value={form.toll_amount} onChange={e=>setForm({...form,toll_amount:+e.target.value})}/></label><label>Enlace del soporte<input type="url" placeholder="https://..." value={form.support_url} onChange={e=>setForm({...form,support_url:e.target.value})}/></label><label className="travel-wide">Observaciones<textarea value={form.observations} onChange={e=>setForm({...form,observations:e.target.value})}/></label><div className="travel-preview"><span>Total estimado</span><strong>{money(preview)}</strong><small>Tarifa según categoría y vigencia.</small></div><button className="primary" disabled={busy}>Registrar solicitud</button></form>{message&&<div className="form-message">{message}</div>}
 <div className="payroll-kpis"><article><span>SOLICITUDES</span><strong>{items.length}</strong></article><article><span>PENDIENTES</span><strong>{items.filter(x=>x.status==="REGISTRADA").length}</strong></article><article><span>APROBADAS</span><strong>{items.filter(x=>x.status==="APROBADA").length}</strong></article><article><span>TOTAL PAGADO</span><strong>{money(items.filter(x=>x.status==="PAGADA").reduce((s,x)=>s+Number(x.total_amount),0))}</strong></article></div><div className="users-table-wrap"><table className="payroll-table"><thead><tr><th>SOLICITUD / EMPLEADO</th><th>COMISIÓN</th><th>PERÍODO</th><th>TARIFA</th><th>TRANSPORTE</th><th>TOTAL</th><th>ESTADO</th><th>ACCIÓN</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><strong>V-{year}-{String(x.request_number).padStart(4,"0")}</strong><small>{x.employee_code} · {x.employee_name}<br/>{x.position_name}</small></td><td>{x.destination}<small>{x.purpose}</small></td><td>{new Date(x.departure_at).toLocaleString("es-DO")}<small>hasta {new Date(x.return_at).toLocaleString("es-DO")} · {x.days} día(s){x.advance_warning&&<b className="travel-warning"> · Fuera del plazo</b>}</small></td><td>{x.category}<small>{money(x.daily_rate)} diarios</small></td><td>{money(Number(x.transport_amount)+Number(x.toll_amount))}</td><td><strong>{money(x.total_amount)}</strong></td><td><span className={`status-pill ${x.status.toLowerCase()}`}>{x.status}</span></td><td>{x.status==="REGISTRADA"&&<><button className="row-action" onClick={()=>transition(x.id,"APROBADA")}>Aprobar</button><button className="row-action danger" onClick={()=>transition(x.id,"RECHAZADA")}>Rechazar</button></>}{x.status==="APROBADA"&&<button className="row-action" onClick={()=>transition(x.id,"PAGADA")}>Marcar pagada</button>}</td></tr>)}{!busy&&!items.length&&<tr><td colSpan={8}>No existen solicitudes para este año.</td></tr>}</tbody></table></div></section>
}
