"use client";
import {useEffect,useMemo,useState} from "react";

type Vacancy={id:string;position_name:string;direction_name:string;department_name:string;division_name:string;section_name:string;center_name:string;execution_fund:string;program:number|null;subproduct:number|null;activity:number|null;monthly_amount:number;available_from:string};
type Area={direction_name:string;department_name:string;vacancy_count:number;monthly_available:number};
const money=(value:number)=>new Intl.NumberFormat("es-DO",{style:"currency",currency:"DOP",maximumFractionDigits:2}).format(value||0);

export default function VacancyDashboard(){
 const now=new Date(),[year,setYear]=useState(now.getFullYear()),[month,setMonth]=useState(now.getMonth()+1),[items,setItems]=useState<Vacancy[]>([]),[areas,setAreas]=useState<Area[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState("");
 useEffect(()=>{let active=true;setLoading(true);fetch(`/api/hr/vacancies?year=${year}&month=${month}`,{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then(data=>{if(active){setItems(Array.isArray(data.items)?data.items:[]);setAreas(Array.isArray(data.areas)?data.areas:[])}}).catch(()=>{if(active){setItems([]);setAreas([])}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[year,month]);
 const filtered=useMemo(()=>items.filter(v=>`${v.position_name} ${v.direction_name} ${v.department_name} ${v.division_name} ${v.section_name}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
 const total=areas.reduce((sum,a)=>sum+Number(a.monthly_available),0);
 return <section className="employee-registry-panel"><div className="direction-strip"><strong>DIRECCIÓN RESPONSABLE</strong><span>Dirección de Recursos Humanos · Vacantes y disponibilidad mensual</span></div><div className="employee-registry-head"><div><span className="eyebrow">CONTROL DE VACANTES</span><h2>Vacantes disponibles por área</h2><p>Cada salida aprobada libera el cargo y suma su sueldo a la disponibilidad mensual del área.</p></div><div><select value={year} onChange={e=>setYear(+e.target.value)}>{Array.from({length:6},(_,i)=>2026+i).map(y=><option key={y}>{y}</option>)}</select><select value={month} onChange={e=>setMonth(+e.target.value)}>{Array.from({length:12},(_,i)=><option key={i} value={i+1}>{new Date(2026,i,1).toLocaleDateString("es-DO",{month:"long"})}</option>)}</select></div></div><div className="technical-kpis"><article><span>VACANTES DISPONIBLES</span><strong>{items.length}</strong></article><article><span>ÁREAS CON VACANTES</span><strong>{areas.length}</strong></article><article><span>DISPONIBILIDAD MENSUAL</span><strong>{money(total)}</strong></article><article><span>PERÍODO</span><strong>{String(month).padStart(2,"0")}/{year}</strong></article></div><div className="vacancy-area-grid">{areas.map(a=><article key={`${a.direction_name}-${a.department_name}`}><span>{a.direction_name||"Sin dirección"}</span><strong>{a.department_name||"Nivel de dirección"}</strong><small>{a.vacancy_count} vacante{a.vacancy_count===1?"":"s"}</small><b>{money(Number(a.monthly_available))}</b></article>)}</div><div className="technical-card"><div className="users-card-head"><div><h2>Detalle de puestos disponibles</h2><p>Clasificación institucional y presupuestaria del puesto liberado.</p></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cargo o área"/></div>{loading?<div className="users-empty">Cargando vacantes…</div>:!filtered.length?<div className="technical-empty"><strong>No hay vacantes para este período</strong><span>Las vacantes aparecerán al aprobar la salida de un colaborador.</span></div>:<div className="users-table-wrap"><table className="employee-registry-table"><thead><tr><th>CARGO</th><th>DIRECCIÓN</th><th>DEPENDENCIA</th><th>CLASIFICACIÓN</th><th>DISPONIBLE DESDE</th><th>DISPONIBILIDAD MENSUAL</th></tr></thead><tbody>{filtered.map(v=><tr key={v.id}><td><strong>{v.position_name}</strong></td><td>{v.direction_name||"—"}</td><td><strong>{v.department_name||"—"}</strong><small>{[v.division_name,v.section_name,v.center_name].filter(Boolean).join(" · ")}</small></td><td>Fondo {v.execution_fund||"—"}<small>{[v.program,v.subproduct,v.activity].map(x=>x??"—").join("/")}</small></td><td>{new Date(`${v.available_from}T12:00:00`).toLocaleDateString("es-DO")}</td><td>{money(Number(v.monthly_amount))}</td></tr>)}</tbody></table></div>}</div></section>
}
