"use client";

import { useEffect, useMemo, useState } from "react";

type Permissions = { registrar_cubicaciones?:boolean; revisar_cubicaciones?:boolean; libramiento_cubicaciones?:boolean; pagar_cubicaciones?:boolean; ver_resumen?:boolean; ver_proyectos?:boolean; ver_proyectos_tecnicos?:boolean; ver_cubicaciones?:boolean; ver_calendario?:boolean; ver_reportes?:boolean };
type AppUser = { id: string; username: string; full_name: string; area: string; role: string; permissions?:Permissions; must_change_password?:boolean };
type ManagedUser = AppUser & { active: boolean; created_at: string; last_login_at: string | null };
type TechnicalProject = { id:string; budget_account:string; procurement_process:string; project_year:number; supplier_contractor:string; snip_code:string; has_lot:boolean; lot_number:string; work_name:string; fixed_assets:string; municipality:string; district:string; sector:string; population:number; linear_meters:number|null; budgeted_amount:number; appropriation_amount:number; awarded_amount:number; advance_20_amount:number; fixed_asset_paid_amount:number; measurement_count:number; measurement_status:string; total_measured:number; total_paid:number; work_status:string; work_progress:number; created_at:string };
type AuditEntry={action:string;from_status:string|null;to_status:string;comments:string;created_at:string;user_name:string};
type Measurement={id:string;project_id:string;measurement_number:number;code:string;amount:number;progress_increment:number;description:string;status:"Registrada"|"Revisada"|"Libramiento"|"Pagada";work_name:string;snip_code:string;sector:string;municipality:string;registered_by_name:string;created_at:string;audit:AuditEntry[]};
type CatalogItem={id:string;code?:string;name?:string;description:string;active:boolean};
type ProjectCatalogs={accounts:CatalogItem[];processes:CatalogItem[];suppliers:CatalogItem[]};
type DirectionModule={label:string;section:string;icon:string;permission?:keyof Permissions;roles?:string[];adminOnly?:boolean};
type InstitutionalDirection={name:string;shortName:string;icon:string;area?:string;modules:DirectionModule[]};
type OrganizationUnit={name:string;children?:OrganizationUnit[]};

const institutionalDirections:InstitutionalDirection[]=[
 {name:"Dirección General",shortName:"Dirección General",icon:"⌂",modules:[{label:"Resumen institucional",section:"Resumen",icon:"▦",permission:"ver_resumen"},{label:"Proyectos institucionales",section:"Proyectos",icon:"▤",permission:"ver_proyectos"},{label:"Reportes ejecutivos",section:"Reportes",icon:"▥",permission:"ver_reportes"}]},
 {name:"Dirección de Recursos Humanos",shortName:"Recursos Humanos",icon:"♙",area:"Gestión Humana",modules:[{label:"Gestión de Recursos Humanos",section:"Recursos Humanos",icon:"◉"},{label:"Estructura organizacional",section:"Estructura Organizacional",icon:"⌘"}]},
 {name:"Dirección Técnica",shortName:"Dirección Técnica",icon:"⌁",area:"Técnica",modules:[{label:"Proyectos y obras",section:"Proyectos Técnicos",icon:"▤",permission:"ver_proyectos_tecnicos"},{label:"Cubicaciones",section:"Cubicaciones",icon:"▧",permission:"ver_cubicaciones"}]},
 {name:"Dirección de Planificación y Desarrollo",shortName:"Planificación y Desarrollo",icon:"◇",modules:[{label:"Proyectos institucionales",section:"Proyectos",icon:"▤",permission:"ver_proyectos"},{label:"Indicadores y reportes",section:"Reportes",icon:"▥",permission:"ver_reportes"}]},
 {name:"Dirección Administrativa y Financiera",shortName:"Administrativa y Financiera",icon:"$",area:"Financiera",modules:[{label:"Presupuesto y ejecución",section:"Proyectos Técnicos",icon:"$",permission:"ver_proyectos_tecnicos"},{label:"Compras, cuentas y proveedores",section:"Catálogos",icon:"▣",roles:["Administrador","Director"]},{label:"Libramientos y pagos",section:"Cubicaciones",icon:"▧",permission:"ver_cubicaciones"}]},
 {name:"Configuración",shortName:"Configuración",icon:"⚙",modules:[{label:"Usuarios y roles",section:"Usuarios",icon:"♙",adminOnly:true}]},
];

const organizationalStructure:OrganizationUnit={name:"Dirección General",children:[
 {name:"Dirección de Comunicaciones",children:[{name:"División de Relaciones Públicas",children:[{name:"Sección de Prensa"}]},{name:"División de Participación Social y Ciudadana"},{name:"Sección de Protocolo y Eventos"},{name:"Sección de Redes Sociales y Medios Digitales"}]},
 {name:"Dirección de Recursos Humanos",children:[{name:"Sección de Registro, Control y Nómina"},{name:"Sección de Evaluación del Desempeño y Capacitaciones"},{name:"Sección de Organización del Trabajo y Compensaciones"}]},
 {name:"Dirección Administrativa y Financiera",children:[{name:"Departamento Administrativo",children:[{name:"Sección de Activo Fijo"},{name:"Sección de Transportación"},{name:"División de Servicios Generales",children:[{name:"Sección de Seguridad"},{name:"Sección de Mayordomía"},{name:"Sección de Mantenimiento y Reparación"},{name:"Sección de Archivo y Correspondencia"},{name:"Sección de Almacén y Suministro"}]}]},{name:"Departamento Financiero",children:[{name:"Sección de Contabilidad"},{name:"Sección de Presupuesto"},{name:"Sección de Tesorería"}]},{name:"Departamento de Contrataciones Públicas",children:[{name:"Sección de Planeación y Preparación de Contrataciones"},{name:"Sección de Gestión Contractual"}]}]},
 {name:"Dirección Técnica",children:[{name:"Departamento de Aguas Residuales y Saneamiento",children:[{name:"Sección de Operación y Mantenimiento de Redes de Aguas Residuales"},{name:"Sección de Tratamiento de Aguas Residuales"},{name:"Sección de Control de Calidad de Aguas Residuales"}]},{name:"Departamento de Operación y Mantenimiento",children:[{name:"Sección de Operación y Distribución de Agua Potable"},{name:"Sección de Catastro de Redes de Agua Potable"},{name:"Sección de Electromecánica"},{name:"Sección de Mantenimiento de Redes"},{name:"Sección de Operación y Mantenimiento de Redes de Zonas Periféricas"}]},{name:"Departamento de Producción y Tratamiento de Agua Potable",children:[{name:"Sección de Tratamiento de Agua Potable"},{name:"Sección de Laboratorio de Agua Potable"},{name:"Sección de Obra de Toma"},{name:"Sección de Control y Calidad de Agua Potable"}]},{name:"Departamento de Ingeniería",children:[{name:"Sección de Construcción"},{name:"Sección de Diseño y Presupuesto"},{name:"Sección de Fiscalización y Control de Obras"}]}]},
 {name:"Dirección Comercial",children:[{name:"Departamento de Gestión Comercial",children:[{name:"Sección de Gestión de Cobros"},{name:"Sección de Facturación"},{name:"Sección de Atención al Cliente"},{name:"Centros de Pagos Externos"},{name:"Centros de Servicio al Cliente"}]},{name:"Departamento de Gestión Operativa",children:[{name:"Sección de Catastro de Usuarios"},{name:"Sección de Micromedición"},{name:"Sección de Corte y Reconexión"}]}]},
 {name:"Dirección de Planificación y Desarrollo",children:[{name:"Departamento de Desarrollo Institucional y Calidad en la Gestión"},{name:"Sección de Cooperación Internacional"},{name:"Departamento de Formulación, Monitoreo y Evaluación de Planes, Programas y Proyectos"}]},
 {name:"Departamento de Tecnología de la Información y Comunicación (TIC)",children:[{name:"Sección de Administración de Servicios TIC"},{name:"Sección de Operaciones TIC"}]},
 {name:"Departamento de Control y Análisis de Operaciones"},
 {name:"Departamento Jurídico"},
 {name:"Oficina de Acceso a la Información"}
]};

function OrganizationBranch({unit,level=0}:{unit:OrganizationUnit;level?:number}){return <div className={`organization-branch level-${Math.min(level,3)}`}><div className="organization-unit"><i>{level===0?"DG":level===1?"D":"•"}</i><span>{unit.name}</span>{unit.children&&<b>{unit.children.length}</b>}</div>{unit.children&&<div className="organization-children">{unit.children.map(child=><OrganizationBranch key={child.name} unit={child} level={level+1}/>)}</div>}</div>}

type Area = "Todos" | "Institucional" | "Gestión Humana" | "Financiera" | "Técnica" | "Comercial";
type Project = { id: number; code: string; name: string; area: Exclude<Area, "Todos">; owner: string; progress: number; budget: number; spent: number; status: "En curso" | "En riesgo" | "Completado"; due: string };

const initialProjects: Project[] = [
  { id: 1, code: "PI-026", name: "Plan estratégico institucional 2026", area: "Institucional", owner: "Dirección Ejecutiva", progress: 72, budget: 3800000, spent: 2460000, status: "En curso", due: "30 Sep" },
  { id: 2, code: "GH-014", name: "Evaluación de desempeño y competencias", area: "Gestión Humana", owner: "Laura Méndez", progress: 58, budget: 1250000, spent: 710000, status: "En curso", due: "18 Ago" },
  { id: 3, code: "GF-031", name: "Automatización presupuestaria", area: "Financiera", owner: "Carlos Peralta", progress: 43, budget: 5600000, spent: 3190000, status: "En riesgo", due: "12 Ago" },
  { id: 4, code: "GT-019", name: "Rehabilitación red de distribución norte", area: "Técnica", owner: "Ing. Mariel Soto", progress: 81, budget: 18400000, spent: 14230000, status: "En curso", due: "05 Oct" },
  { id: 5, code: "GC-022", name: "Actualización del catastro de usuarios", area: "Comercial", owner: "Samuel Peña", progress: 66, budget: 7900000, spent: 4810000, status: "En curso", due: "22 Sep" },
  { id: 6, code: "GT-011", name: "Optimización estación de bombeo central", area: "Técnica", owner: "José Rosario", progress: 100, budget: 9200000, spent: 8940000, status: "Completado", due: "Completado" },
];

const areaData = [
  { name: "Institucional", icon: "⌂", color: "blue", metric: "12", label: "iniciativas activas", progress: 74 },
  { name: "Gestión Humana", icon: "♙", color: "violet", metric: "428", label: "colaboradores", progress: 68 },
  { name: "Financiera", icon: "$", color: "amber", metric: "84.6%", label: "ejecución presupuestaria", progress: 85 },
  { name: "Técnica", icon: "⌁", color: "cyan", metric: "19", label: "proyectos en campo", progress: 71 },
  { name: "Comercial", icon: "↗", color: "green", metric: "92.3%", label: "recaudación mensual", progress: 92 },
];

const money = (value: number) => new Intl.NumberFormat("es-DO", { style: "currency", currency: "DOP", maximumFractionDigits: 0 }).format(value);

function TechnicalProjectModal({ project,catalogs,onClose,onSubmit }: { project: TechnicalProject | null;catalogs:ProjectCatalogs;onClose: () => void; onSubmit: (e: React.FormEvent<HTMLFormElement>) => void }) {
  return <div className="modal-backdrop technical-backdrop" onMouseDown={onClose}><form key={project?.id || "new"} className="modal technical-modal" onSubmit={onSubmit} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">DIRECCIÓN TÉCNICA</span><h2>{project ? "Editar proyecto" : "Registrar proyecto institucional"}</h2></div><button type="button" onClick={onClose}>×</button></div>
    <div className="form-section"><h3>1. Identificación y contratación</h3><div className="technical-form-grid"><label className="span-2">Obra<input name="work_name" required defaultValue={project?.work_name}/></label><label>Cuenta presupuestaria<input name="budget_account" list="budget-accounts" required defaultValue={project?.budget_account}/><datalist id="budget-accounts">{catalogs.accounts.filter(x=>x.active).map(x=><option key={x.id} value={x.code}/>)}</datalist></label><label>Proceso de compra o contratación<input name="procurement_process" list="procurement-processes" required defaultValue={project?.procurement_process}/><datalist id="procurement-processes">{catalogs.processes.filter(x=>x.active).map(x=><option key={x.id} value={x.code}/>)}</datalist></label><label>Año de realización<input name="project_year" type="number" min="2000" max="2100" required defaultValue={project?.project_year || new Date().getFullYear()}/></label><label>Proveedor o contratista<input name="supplier_contractor" list="suppliers" required defaultValue={project?.supplier_contractor}/><datalist id="suppliers">{catalogs.suppliers.filter(x=>x.active).map(x=><option key={x.id} value={x.name}/>)}</datalist></label><label>Código SNIP<input name="snip_code" defaultValue={project?.snip_code}/></label><label>No. de lote<input name="lot_number" defaultValue={project?.lot_number}/></label><label className="check-label"><input name="has_lot" type="checkbox" defaultChecked={project?.has_lot}/> El proyecto posee lote</label><label>Activos fijos<input name="fixed_assets" defaultValue={project?.fixed_assets}/></label></div></div>
    <div className="form-section"><h3>2. Ubicación e impacto</h3><div className="technical-form-grid"><label>Municipio<input name="municipality" required defaultValue={project?.municipality}/></label><label>Distrito<input name="district" defaultValue={project?.district}/></label><label>Sector<input name="sector" defaultValue={project?.sector}/></label><label>Población beneficiada<input name="population" type="number" min="0" defaultValue={project?.population || 0}/></label><label>Metros lineales (cuando aplique)<input name="linear_meters" type="number" min="0" step="0.01" defaultValue={project?.linear_meters || ""}/></label></div></div>
    <div className="form-section"><h3>3. Gestión financiera</h3><div className="technical-form-grid"><label>Monto presupuestado<input name="budgeted_amount" type="number" min="0" step="0.01" defaultValue={project?.budgeted_amount || 0}/></label><label>Monto en apropiación<input name="appropriation_amount" type="number" min="0" step="0.01" defaultValue={project?.appropriation_amount || 0}/></label><label>Monto adjudicado<input name="awarded_amount" type="number" min="0" step="0.01" defaultValue={project?.awarded_amount || 0}/></label><label>Avance del 20% pagado<input name="advance_20_amount" type="number" min="0" step="0.01" defaultValue={project?.advance_20_amount || 0}/></label><label>Pago de activos fijos<input name="fixed_asset_paid_amount" type="number" min="0" step="0.01" defaultValue={project?.fixed_asset_paid_amount || 0}/></label></div></div>
    <div className="form-section"><h3>4. Cubicaciones y ejecución</h3><div className="technical-form-grid"><label>Cantidad de cubicaciones<input name="measurement_count" type="number" min="0" defaultValue={project?.measurement_count || 0}/></label><label>Estatus de cubicaciones<select name="measurement_status" defaultValue={project?.measurement_status || "Pendiente"}>{["Pendiente","En revisión","Aprobada","Observada","Pagada"].map(x=><option key={x}>{x}</option>)}</select></label><label>Total cubicado<input name="total_measured" type="number" min="0" step="0.01" defaultValue={project?.total_measured || 0}/></label><label>Total pagado (calculado)<input name="total_paid" type="number" readOnly value={project?.total_paid || 0}/></label><label>Estatus de obra<select name="work_status" defaultValue={project?.work_status || "Planificación"}>{["Planificación","En contratación","Adjudicada","En ejecución","Pausada","Finalizada","Cancelada"].map(x=><option key={x}>{x}</option>)}</select></label><label>Avance de obra (%)<input name="work_progress" type="number" min="0" max="100" step="0.01" defaultValue={project?.work_progress || 0}/></label></div></div>
    <div className="modal-actions"><button type="button" className="outline" onClick={onClose}>Cancelar</button><button className="primary">Guardar proyecto</button></div></form></div>;
}

function MeasurementModal({ projects,onClose,onSubmit }:{projects:TechnicalProject[];onClose:()=>void;onSubmit:(e:React.FormEvent<HTMLFormElement>)=>void}){
  const [selected,setSelected]=useState(projects[0]?.id||""); const project=projects.find(item=>item.id===selected);
  return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal measurement-modal" onSubmit={onSubmit} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">NUEVA CUBICACIÓN</span><h2>Registrar etapa de cubicación</h2></div><button type="button" onClick={onClose}>×</button></div><label>Seleccionar código, obra y ubicación<select name="projectId" required value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Seleccione una obra</option>{projects.map(item=><option value={item.id} key={item.id}>{item.snip_code||"Sin SNIP"} · {item.work_name} · {[item.municipality,item.district,item.sector].filter(Boolean).join(" / ")||"Sin ubicación"}</option>)}</select></label>{project&&<div className="project-context"><div><span>CÓDIGO SNIP</span><strong>{project.snip_code||"No especificado"}</strong></div><div><span>OBRA</span><strong>{project.work_name}</strong></div><div><span>MUNICIPIO</span><strong>{project.municipality||"No especificado"}</strong></div><div><span>DISTRITO</span><strong>{project.district||"No especificado"}</strong></div><div><span>SECTOR</span><strong>{project.sector||"No especificado"}</strong></div></div>}<div className="form-row"><label>Monto de la …8791 tokens truncated…strong>{money(technicalProjects.reduce((sum,p)=>sum+Number(p.total_measured),0))}</strong></article><article><span>TOTAL PAGADO</span><strong>{money(technicalProjects.reduce((sum,p)=>sum+Number(p.total_paid),0))}</strong></article></div>
            {technicalMessage && <div className={technicalMessage.startsWith("Proyecto guardado") ? "users-success" : "auth-error"}>{technicalMessage}</div>}
            <div className="technical-card"><div className="users-card-head"><div><h2>Cartera de obras y proyectos técnicos</h2><p>Control presupuestario, contractual, territorial y de ejecución.</p></div><button className="primary" onClick={()=>{setEditingTechnical(null);setShowTechnicalForm(true)}}>＋ Registrar proyecto</button></div>
              {technicalLoading ? <div className="users-empty">Cargando proyectos…</div> : technicalProjects.length===0 ? <div className="technical-empty"><strong>No hay proyectos técnicos registrados</strong><span>Registra la primera obra para iniciar el seguimiento interdireccional.</span></div> : <div className="users-table-wrap"><table className="technical-table"><thead><tr><th>OBRA / SNIP</th><th>UBICACIÓN</th><th>CONTRATISTA</th><th>PRESUPUESTO</th><th>CUBICADO / PAGADO</th><th>AVANCE</th><th>ESTATUS</th><th></th></tr></thead><tbody>{technicalProjects.map(project=><tr key={project.id}><td><strong>{project.work_name}</strong><small>{project.snip_code || "Sin código SNIP"} · {project.project_year}</small></td><td><b>{project.municipality}</b><small>{[project.district,project.sector].filter(Boolean).join(" · ")}</small></td><td>{project.supplier_contractor}</td><td><b>{money(Number(project.budgeted_amount))}</b><small>Adjudicado: {money(Number(project.awarded_amount))}</small></td><td><b>{money(Number(project.total_measured))}</b><small>Pagado: {money(Number(project.total_paid))}</small></td><td><div className="tech-progress"><i><em style={{width:`${project.work_progress}%`}} /></i><b>{project.work_progress}%</b></div></td><td><span className="work-status">{project.work_status}</span><small>{project.measurement_status}</small></td><td><button className="row-action" onClick={()=>{setEditingTechnical(project);setShowTechnicalForm(true)}}>Editar</button></td></tr>)}</tbody></table></div>}
            </div>
          </section>}

          {section === "Cubicaciones" && <section className="measurements-panel">
            <div className="workflow-head"><div><span>FLUJO DE APROBACIÓN</span><h2>Cubicaciones de obras</h2><p>Cada cubicación avanza por la línea de mando antes de afectar la ejecución financiera y física.</p></div><button className="primary" onClick={()=>setShowMeasurementForm(true)} disabled={!technicalProjects.length}>＋ Registrar cubicación</button></div>
            <div className="workflow-line">{["Registrada","Revisada","Libramiento","Pagada"].map((stage,index)=><div key={stage}><i>{index+1}</i><strong>{stage}</strong><span>{index===0?"Sin afectación":index===1?"Validación técnica":index===2?"Trámite financiero":"Impacta obra"}</span></div>)}</div>
            <div className="measurement-kpis"><article><span>REGISTRADAS</span><strong>{measurements.filter(x=>x.status==="Registrada").length}</strong></article><article><span>EN REVISIÓN / LIBRAMIENTO</span><strong>{measurements.filter(x=>x.status==="Revisada"||x.status==="Libramiento").length}</strong></article><article><span>PAGADAS</span><strong>{measurements.filter(x=>x.status==="Pagada").length}</strong></article><article><span>MONTO PAGADO</span><strong>{money(measurements.filter(x=>x.status==="Pagada").reduce((s,x)=>s+Number(x.amount),0))}</strong></article></div>
            {measurementMessage&&<div className={measurementMessage.includes("correctamente")||measurementMessage.includes("avanzada")?"users-success":"auth-error"}>{measurementMessage}</div>}
            <div className="technical-card"><div className="users-card-head"><div><h2>Expedientes de cubicación</h2><p>Etapas, responsables y trazabilidad completa.</p></div></div>{measurementsLoading?<div className="users-empty">Cargando cubicaciones…</div>:measurements.length===0?<div className="technical-empty"><strong>No hay cubicaciones registradas</strong><span>Seleccione una obra y registre su primera etapa de cubicación.</span></div>:<div className="users-table-wrap"><table className="measurement-table"><thead><tr><th>CÓDIGO / ETAPA</th><th>OBRA Y SECTOR</th><th>MONTO</th><th>AVANCE</th><th>REGISTRADO POR</th><th>ESTATUS</th><th>ACCIONES</th></tr></thead><tbody>{measurements.map(item=><tr key={item.id}><td><strong>{item.code}</strong><small>Cubicación No. {item.measurement_number}</small></td><td><b>{item.work_name}</b><small>{item.snip_code||"Sin SNIP"} · {item.sector||item.municipality}</small></td><td><b>{money(Number(item.amount))}</b><small>{item.status==="Pagada"?"Aplicado a la obra":"Sin afectar presupuesto"}</small></td><td><b>＋{item.progress_increment}%</b><small>{item.status==="Pagada"?"Avance aplicado":"Pendiente de pago"}</small></td><td>{item.registered_by_name}<small>{new Date(item.created_at).toLocaleDateString("es-DO")}</small></td><td><span className={`measurement-status status-${item.status.toLowerCase()}`}>{item.status}</span></td><td><div className="measurement-actions"><button className="row-action" onClick={()=>setAuditMeasurement(item)}>Auditoría</button>{canAdvanceMeasurement(item.status)&&<button className="advance-action" onClick={()=>advanceMeasurement(item)}>Avanzar →</button>}</div></td></tr>)}</tbody></table></div>}</div>
          </section>}

          <div className={section === "Usuarios" || section === "Catálogos" || section === "Proyectos Técnicos" || section === "Cubicaciones" || section === "Recursos Humanos" || section === "Estructura Organizacional" || section === "Acceso restringido" ? "section-hidden" : ""}>

          <section className="hero-grid">
            <article className="score-card"><div className="score-top"><div><span>ÍNDICE DE DESEMPEÑO</span><strong>78.4</strong><small>/100</small></div><div className="trend">↗ 6.2%</div></div><div className="score-track"><i style={{ width: "78.4%" }} /></div><div className="score-meta"><span>Planificado <b>82%</b></span><span>Ejecutado <b>74%</b></span><span>Eficiencia <b>79%</b></span></div></article>
            <article className="deadline-card"><div className="mini-title"><span>◷</span><div><strong>Próximo hito crítico</strong><small>En 8 días</small></div></div><h3>Cierre presupuestario Q2</h3><p>Consolidación y entrega de ejecución trimestral.</p><div className="deadline-foot"><span>Gestión Financiera</span><b>23 JUL</b></div></article>
          </section>

          <section className="kpis">
            <article><span>Proyectos activos</span><strong>{projects.filter(p => p.status !== "Completado").length}</strong><small className="up">↗ 3 este mes</small></article>
            <article><span>Avance promedio</span><strong>{totals.avg}%</strong><small className="up">↗ 4.1% vs. junio</small></article>
            <article><span>Presupuesto total</span><strong>RD$ {(totals.budget / 1000000).toFixed(1)}M</strong><small>{Math.round(totals.spent / totals.budget * 100)}% ejecutado</small></article>
            <article><span>Requieren atención</span><strong className="danger">{projects.filter(p => p.status === "En riesgo").length}</strong><small className="danger">Revisar hoy</small></article>
          </section>

          <div className="section-title"><div><h2>Desempeño por área</h2><p>Progreso frente a las metas del período</p></div><button onClick={() => { setSection("Proyectos"); setFilter("Todos"); }}>Ver todos los proyectos →</button></div>
          <section className="area-grid">{areaData.map(a => <article key={a.name} onClick={() => { setSection("Proyectos"); setFilter(a.name as Area); }}><div className={`area-icon ${a.color}`}>{a.icon}</div><div className="area-copy"><strong>{a.name}</strong><span>{a.metric}</span><small>{a.label}</small></div><div className="area-progress"><div><span>Progreso</span><b>{a.progress}%</b></div><i><em style={{ width: `${a.progress}%` }} /></i></div></article>)}</section>

          <div className="section-title project-title"><div><h2>Cartera de proyectos</h2><p>Estado de las iniciativas institucionales</p></div><select value={filter} onChange={e => setFilter(e.target.value as Area)}>{["Todos", ...areaData.map(a => a.name)].map(x => <option key={x}>{x}</option>)}</select></div>
          <section className="table-card"><div className="table-wrap"><table><thead><tr><th>PROYECTO</th><th>ÁREA</th><th>RESPONSABLE</th><th>AVANCE</th><th>PRESUPUESTO</th><th>ESTADO</th><th>ENTREGA</th></tr></thead><tbody>{filtered.map(p => <tr key={p.id}><td><b>{p.code}</b><strong>{p.name}</strong></td><td><span className="area-pill">{p.area}</span></td><td>{p.owner}</td><td><div className="progress-cell"><i><em style={{ width: `${p.progress}%` }} /></i></div><b>{p.progress}%</b></td><td><b>{money(p.budget)}</b><small>{Math.round(p.spent / p.budget * 100)}% usado</small></td><td><span className={`status ${p.status.replace(" ", "-").toLowerCase()}`}>● {p.status}</span></td><td>{p.due}</td></tr>)}</tbody></table>{filtered.length === 0 && <div className="empty">No se encontraron proyectos con esos criterios.</div>}</div></section>
          </div>
        </div>
      </main>

      {showForm && <div className="modal-backdrop" onMouseDown={() => setShowForm(false)}><form className="modal" onSubmit={addProject} onMouseDown={e => e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">NUEVA INICIATIVA</span><h2>Registrar proyecto</h2></div><button type="button" onClick={() => setShowForm(false)}>×</button></div><label>Nombre del proyecto<input name="name" required placeholder="Ej. Ampliación de cobertura rural" /></label><div className="form-row"><label>Área<select name="area">{areaData.map(a => <option key={a.name}>{a.name}</option>)}</select></label><label>Responsable<input name="owner" required placeholder="Nombre o unidad" /></label></div><div className="form-row"><label>Presupuesto (RD$)<input name="budget" required type="number" min="0" placeholder="0" /></label><label>Fecha de entrega<input name="due" required type="date" /></label></div><div className="modal-actions"><button type="button" className="outline" onClick={() => setShowForm(false)}>Cancelar</button><button className="primary">Crear proyecto</button></div></form></div>}
      {showCreateUser&&<div className="modal-backdrop" onMouseDown={()=>setShowCreateUser(false)}><form className="modal technical-modal" onSubmit={createManagedUser} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">ADMINISTRACIÓN</span><h2>Crear usuario institucional</h2><p>La contraseña será temporal y deberá cambiarse en el primer acceso.</p></div><button type="button" onClick={()=>setShowCreateUser(false)}>×</button></div><div className="technical-form-grid"><label>Nombre completo<input name="fullName" required minLength={3}/></label><label>Nombre de usuario<input name="username" required minLength={3} autoCapitalize="none"/></label><label>Contraseña temporal<input name="password" required minLength={8} type="password"/></label><label>Área<select name="area">{areaData.map(a=><option key={a.name}>{a.name}</option>)}</select></label><label>Rol<select name="role">{["Usuario","Consulta","Analista","Supervisor","Director","Administrador"].map(role=><option key={role}>{role}</option>)}</select></label></div><div className="form-section"><h3>Permisos de vista iniciales</h3><div className="permission-toggles create-permissions">{[["ver_resumen","Resumen"],["ver_proyectos","Proyectos"],["ver_proyectos_tecnicos","Proyectos Técnicos"],["ver_cubicaciones","Cubicaciones"],["ver_calendario","Calendario"],["ver_reportes","Reportes"]].map(([key,label])=><label key={key}><input name={key} type="checkbox" defaultChecked/>{label}</label>)}</div></div><div className="modal-actions"><button type="button" className="outline" onClick={()=>setShowCreateUser(false)}>Cancelar</button><button className="primary">Crear usuario</button></div></form></div>}
      {showCatalogForm&&<div className="modal-backdrop" onMouseDown={()=>setShowCatalogForm(null)}><form className="modal" onSubmit={createCatalogItem} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">NUEVO REGISTRO</span><h2>{showCatalogForm==="account"?"Cuenta presupuestaria":showCatalogForm==="process"?"Proceso de compra o contratación":"Proveedor o contratista"}</h2></div><button type="button" onClick={()=>setShowCatalogForm(null)}>×</button></div>{showCatalogForm==="supplier"?<label>Nombre<input name="name" required/></label>:<label>Código<input name="code" required/></label>}<label>Descripción<input name="description"/></label><div className="modal-actions"><button type="button" className="outline" onClick={()=>setShowCatalogForm(null)}>Cancelar</button><button className="primary">Guardar</button></div></form></div>}
      {showTechnicalForm && <TechnicalProjectModal project={editingTechnical} catalogs={catalogs} onClose={()=>setShowTechnicalForm(false)} onSubmit={saveTechnicalProject} />}
      {showMeasurementForm && <MeasurementModal projects={technicalProjects} onClose={()=>setShowMeasurementForm(false)} onSubmit={createMeasurement}/>} 
      {auditMeasurement && <AuditModal measurement={auditMeasurement} onClose={()=>setAuditMeasurement(null)}/>} 
    </div>
  );
}
