param(
  [Parameter(Mandatory=$true)][string]$Workbook,
  [string]$Output = "supabase/project_data_refresh.sql"
)
$ErrorActionPreference='Stop'
$culture=[System.Globalization.CultureInfo]::InvariantCulture
$sourceHash=(Get-FileHash -LiteralPath $Workbook -Algorithm SHA256).Hash.ToLowerInvariant()
function SqlText($value){ if($null -eq $value){return "''"}; return "'"+([string]$value).Trim().Replace("'","''")+"'" }
function Num($value){ if($null -eq $value -or [string]::IsNullOrWhiteSpace([string]$value)){return '0'}; return ([decimal]$value).ToString('0.################',$culture) }
function IntNum($value,$default=0){ if($null -eq $value -or [string]::IsNullOrWhiteSpace([string]$value)){return [string]$default}; return [string][int][decimal]$value }
function Stage($value){ $s=([string]$value).Trim().ToLowerInvariant(); if($s -eq 'pago'){return 'Pagada'}; if($s -like '*libramiento*'){return 'Libramiento'}; if($s){return 'Cubicada'}; return 'Pendiente' }
$excel=New-Object -ComObject Excel.Application
$excel.Visible=$false;$excel.DisplayAlerts=$false
try{
  $book=$excel.Workbooks.Open($Workbook,$null,$true);$sheet=$book.Worksheets.Item(1);$values=$sheet.UsedRange.Value2
  $projects=@();$measurements=@();$catalogs=@{account=@{};process=@{};supplier=@{};municipality=@{};district=@{};sector=@{};work_type=@{};work_status=@{}}
  for($r=2;$r -le $sheet.UsedRange.Rows.Count;$r++){
    if([string]::IsNullOrWhiteSpace([string]($values[$r,9]))){continue}
    $id=[guid]::NewGuid().ToString();$type=([string]($values[$r,8])).Trim();$isAsset=$type.ToLowerInvariant().Contains('activos fijos')
    $year=IntNum ($values[$r,3]) 2026;$budget=Num ($values[$r,15]);$appropriation=Num ($values[$r,16]);$awarded=Num ($values[$r,17])
    $advance=Num ($values[$r,19]);$advanceStatus=Stage ($values[$r,18]);$assetPaid=Num ($values[$r,21]);$assetStatus=Stage ($values[$r,20])
    $progress=[decimal](Num ($values[$r,39]));if($progress -le 1){$progress*=100};$progressText=$progress.ToString('0.##',$culture)
    $measurementRows=@();for($n=1;$n -le 7;$n++){ $statusCol=22+(($n-1)*2);$amountCol=23+(($n-1)*2);$amount=[decimal](Num ($values[$r,$amountCol]));if($amount -gt 0){$measurementRows+=@{number=$n;amount=$amount;status=(Stage ($values[$r,$statusCol]))}} }
    $measured=[decimal]0;$paid=[decimal]0;foreach($measurement in $measurementRows){$measured+=[decimal]$measurement.amount;if($measurement.status -eq 'Pagada'){$paid+=[decimal]$measurement.amount}}
    $overall='Pendiente';if($measurementRows.status -contains 'Pagada'){$overall='Pagada'}elseif($measurementRows.status -contains 'Libramiento'){$overall='Libramiento'}elseif($measurementRows.Count){$overall='Cubicada'}
    $account=([string]($values[$r,1])).Trim();$process=([string]($values[$r,2])).Trim();$supplier=([string]($values[$r,4])).Trim();$municipality=([string]($values[$r,10])).Trim();$district=([string]($values[$r,11])).Trim();$sector=([string]($values[$r,12])).Trim();$status=([string]($values[$r,38])).Trim();$description=([string]($values[$r,9])).Trim()
    if(!$process){$process='Sin proceso registrado'};if(!$supplier){$supplier='Sin Proveedor'};if(!$municipality){$municipality='Sin municipio'};if(!$status){$status='Planificación'}
    foreach($pair in @(@('account',$account),@('process',$process),@('supplier',$supplier),@('municipality',$municipality),@('district',$district),@('sector',$sector),@('work_type',$description),@('work_status',$status))){if($pair[1]){$catalogs[$pair[0]][$pair[1]]=$true}}
    $projects+=@{id=$id;row=$r;account=$account;process=$process;year=$year;supplier=$supplier;snip=([string]($values[$r,5])).Trim();lot=(([string]($values[$r,6])).Trim()+' '+([string]($values[$r,7])).Trim()).Trim();work=$description;fixed=if($isAsset){$type}else{''};workType=$description;municipality=$municipality;district=$district;sector=$sector;population=(IntNum ($values[$r,13]));meters=(Num ($values[$r,14]));budget=$budget;appropriation=$appropriation;awarded=$awarded;advance=$advance;advanceStatus=$advanceStatus;assetPaid=$assetPaid;assetStatus=$assetStatus;count=$measurementRows.Count;measurementStatus=$overall;measured=$measured.ToString('0.##',$culture);paidMeasurements=$paid.ToString('0.##',$culture);sourcePaid=(Num ($values[$r,37]));status=$status;progress=$progressText;rawType=$type}
    foreach($m in $measurementRows){$measurements+=@{id=[guid]::NewGuid().ToString();project=$id;row=$r;number=$m.number;amount=$m.amount.ToString('0.##',$culture);status=$m.status;progress=if([decimal]$awarded -gt 0){([decimal]$m.amount*100/[decimal]$awarded).ToString('0.##',$culture)}else{'0'}}}
  }
  $lines=[System.Collections.Generic.List[string]]::new();$lines.Add('-- Generado automaticamente desde BASE DATOS ACTUALIZADA 2.xlsx.');$lines.Add('begin;')
  $lines.Add("create table if not exists public.project_data_imports(id uuid primary key default gen_random_uuid(),source_file text not null,source_hash text not null default '',imported_at timestamptz not null default now(),project_count integer not null,measurement_count integer not null,previous_snapshot jsonb not null default '{}'::jsonb);alter table public.project_data_imports add column if not exists source_hash text not null default '';")
  $lines.Add("alter table public.technical_projects add column if not exists advance_status text not null default 'Pagada',add column if not exists fixed_asset_status text not null default 'Pagada',add column if not exists source_total_paid numeric(18,2) not null default 0,add column if not exists source_row_number integer;")
  $lines.Add("insert into public.project_data_imports(source_file,source_hash,project_count,measurement_count,previous_snapshot) select 'BASE DATOS ACTUALIZADA 2.xlsx','$sourceHash',$($projects.Count),$($measurements.Count),jsonb_build_object('projects',coalesce((select jsonb_agg(to_jsonb(p)) from public.technical_projects p),'[]'::jsonb),'measurements',coalesce((select jsonb_agg(to_jsonb(m)) from public.project_measurements m),'[]'::jsonb));")
  $lines.Add("update public.complete_audit_log set project_id=null,measurement_id=null where project_id is not null or measurement_id is not null;")
  $lines.Add('delete from public.technical_projects;')
  $lines.Add("update public.administrative_catalogs set active=false,updated_at=now() where catalog_type in ('supplier','account','process','municipality','district','sector','work_type','work_status');")
  $lines.Add("update public.budget_account_catalog set active=false,updated_at=now();update public.procurement_process_catalog set active=false,updated_at=now();update public.supplier_catalog set active=false,updated_at=now();")
  foreach($kind in $catalogs.Keys){foreach($name in $catalogs[$kind].Keys){$code=if($kind -in @('account','process')){$name}else{''};$lines.Add("insert into public.administrative_catalogs(catalog_type,code,name,description,active) values("+(SqlText $kind)+','+(SqlText $code)+','+(SqlText $name)+","+(SqlText 'Importado desde BASE DATOS ACTUALIZADA 2.xlsx')+",true) on conflict(catalog_type,lower(code),lower(name)) do update set active=true,updated_at=now();")}}
  foreach($p in $projects){$lines.Add("insert into public.technical_projects(id,budget_account,procurement_process,project_year,supplier_contractor,snip_code,has_lot,lot_number,work_name,fixed_assets,work_type,municipality,district,sector,population,linear_meters,budgeted_amount,appropriation_amount,committed_amount,awarded_amount,advance_20_amount,advance_status,fixed_asset_paid_amount,fixed_asset_status,measurement_count,measurement_status,total_measured,paid_measurements_amount,total_paid,source_total_paid,work_status,work_progress,source_row_number,created_by) values('$($p.id)',"+(SqlText $p.account)+','+(SqlText $p.process)+",$($p.year),"+(SqlText $p.supplier)+','+(SqlText $p.snip)+","+($(if($p.lot){'true'}else{'false'}))+','+(SqlText $p.lot)+','+(SqlText $p.work)+','+(SqlText $p.fixed)+','+(SqlText $p.workType)+','+(SqlText $p.municipality)+','+(SqlText $p.district)+','+(SqlText $p.sector)+",$($p.population),$($p.meters),$($p.budget),$($p.appropriation),0,$($p.awarded),$($p.advance),"+(SqlText $p.advanceStatus)+",$($p.assetPaid),"+(SqlText $p.assetStatus)+",$($p.count),"+(SqlText $p.measurementStatus)+",$($p.measured),$($p.paidMeasurements),0,$($p.sourcePaid),"+(SqlText $p.status)+",$($p.progress),$($p.row),(select id from public.app_users where role='Administrador' order by created_at limit 1));")}
  foreach($m in $measurements){$auditStatus=SqlText $m.status;$lines.Add("insert into public.project_measurements(id,project_id,measurement_number,code,amount,progress_increment,description,status,registered_by,reviewed_by,reviewed_at,released_by,released_at,paid_by,paid_at) values('$($m.id)','$($m.project)',$($m.number),'IMP-R$($m.row)-C$($m.number)',$($m.amount),$($m.progress),'Importada desde Excel',$auditStatus,(select id from public.app_users where role='Administrador' order by created_at limit 1),case when $auditStatus in ('Revisada','Libramiento','Pagada') then (select id from public.app_users where role='Administrador' order by created_at limit 1) end,case when $auditStatus in ('Revisada','Libramiento','Pagada') then now() end,case when $auditStatus in ('Libramiento','Pagada') then (select id from public.app_users where role='Administrador' order by created_at limit 1) end,case when $auditStatus in ('Libramiento','Pagada') then now() end,case when $auditStatus='Pagada' then (select id from public.app_users where role='Administrador' order by created_at limit 1) end,case when $auditStatus='Pagada' then now() end);")}
  $lines.Add("update public.technical_projects set total_paid=(case when advance_status='Pagada' then advance_20_amount else 0 end)+(case when fixed_asset_status='Pagada' then fixed_asset_paid_amount else 0 end)+paid_measurements_amount;")
  $lines.Add("insert into public.budget_account_catalog(code,description) select distinct budget_account,'Importado desde Excel' from public.technical_projects where budget_account<>'' on conflict(code) do update set active=true,updated_at=now();")
  $lines.Add("insert into public.procurement_process_catalog(code,description) select distinct procurement_process,'Importado desde Excel' from public.technical_projects where procurement_process<>'' on conflict(code) do update set active=true,updated_at=now();")
  $lines.Add("insert into public.supplier_catalog(name,description) select distinct supplier_contractor,'Importado desde Excel' from public.technical_projects where supplier_contractor<>'' on conflict(name) do update set active=true,updated_at=now();")
  $lines.Add("update public.technical_projects p set budget_account_catalog_id=a.id from public.budget_account_catalog a where a.code=p.budget_account;update public.technical_projects p set procurement_process_catalog_id=c.id from public.procurement_process_catalog c where c.code=p.procurement_process;update public.technical_projects p set supplier_catalog_id=s.id from public.supplier_catalog s where s.name=p.supplier_contractor;")
  $lines.Add("do `$`$ begin if (select count(*) from public.technical_projects)<>$($projects.Count) then raise exception 'Conteo de proyectos importados invalido';end if;if (select count(*) from public.project_measurements)<>$($measurements.Count) then raise exception 'Conteo de cubicaciones importadas invalido';end if;end `$`$;")
  $lines.Add('commit;');[System.IO.File]::WriteAllLines((Join-Path (Get-Location) $Output),$lines,[System.Text.UTF8Encoding]::new($false))
  Write-Output "Proyectos=$($projects.Count); Cubicaciones=$($measurements.Count); Salida=$Output"
}finally{if($book){$book.Close($false)};$excel.Quit()}
